export const SCENARIOS = [
  {
    id: 'wanderer',
    title: '流浪者 (The Wanderer)',
    description: '你独自一人，身无分文，只有一把生锈的剑和背上的衣服。这是最纯粹的Kenshi体验。',
    difficulty: '普通',
    icon: 'Sword',
    equipment: ['生锈的铁剑', '破旧的裤子'],
    money: 1000,
  },
  {
    id: 'unknown_dream',
    title: '未知梦想',
    description: '你不被任何既定剧本束缚。自行决定来历、携带装备与开局物品，写下属于你的第一章。',
    difficulty: '普通',
    icon: 'Sparkles',
    equipment: ['无'],
    money: 0,
  },
  {
    id: 'slave_master',
    title: '奴隶主启程',
    description:
      '你生来就是联合帝国的上层贵族，财富、权势与奴仆唾手可得。如今你牵着两名私人奴隶踏入赫夫特城，表面风光无限，暗地里却已被反蓄奴者盯上。金钱能买来忠诚，也能买来仇恨——在刀锋与阴谋之间，守住你的地位。',
    difficulty: '困难',
    icon: 'Handcuffs',
    equipment: ['贵族服饰', '短刀', '奴隶镣铐钥匙'],
    money: 8000,
    fixedRegion: 'great_desert',
    fixedTown: '赫夫特城',
    alliedFactions: ['联合城', '商人行会', '奴隶商人'],
    hostileFactions: ['反蓄奴者'],
    companions: [
      {
        race: 'human',
        subrace: 'greenlander',
        level: 1,
        attributes: {
          strength: 12,
          dexterity: 12,
          perception: 10,
          constitution: 12,
          will: 10,
          intelligence: 8,
          charisma: 6,
        },
        name: '私人奴隶A',
        gender: 'male',
        age: 22,
        appearance: {
          eyes: '',
          hairStyle: '',
          hairColor: '',
          bodyType: '消瘦',
          height: 172,
          description: '骨瘦如柴，神情麻木，脖颈有明显镣铐磨痕。',
        },
        traits: [],
        customTraitName: '',
        customTraitDescription: '',
      },
      {
        race: 'human',
        subrace: 'scorchlander',
        level: 1,
        attributes: {
          strength: 10,
          dexterity: 13,
          perception: 10,
          constitution: 11,
          will: 10,
          intelligence: 8,
          charisma: 6,
        },
        name: '私人奴隶B',
        gender: 'female',
        age: 21,
        appearance: {
          eyes: '',
          hairStyle: '',
          hairColor: '',
          bodyType: '消瘦',
          height: 168,
          description: '长期营养不良，眼神空洞，行动谨慎而机械。',
        },
        traits: [],
        customTraitName: '',
        customTraitDescription: '',
      },
    ],
  },
  {
    id: 'human_torso',
    title: '人棍',
    description:
      '你从喙嘴兽的口中捡回一条命，却失去了全部四肢。如今你被困在目之地的沙尔维尔驿站，身无分文、寸步难行。是装上义肢向命运复仇，还是在黄沙中悄然腐朽？',
    difficulty: '极难',
    icon: 'Skull',
    equipment: ['无'],
    money: 0,
    fixedRegion: 'eye_land',
    fixedTown: '沙尔维尔驿站',
  },
  {
    id: 'monster_hunter',
    title: '怪物猎人',
    description:
      '你是没落巨兽猎人家族的最后传人，携祖传巨刃驻守利维坦观测站。面对如山般的巨兽与深海怪影，你要以狩猎证明谁才是这片海岸的终极掠食者。',
    difficulty: '极难',
    icon: 'Sword',
    equipment: ['利维坦狩猎之刃'],
    money: 300,
    fixedRegion: 'leviathan_coast',
    fixedTown: '利维坦观测站',
  },
  {
    id: 'holy_sword',
    title: '大剑',
    description: '你偷走了传说中的圣剑。现在，整个帝国都在追捕你。你拥有强大的武器，但没有未来。',
    difficulty: '困难',
    icon: 'ShieldAlert',
    equipment: ['大剑 (铭刃)', '破旧的衣服', '通缉令 (20,000c)'],
    money: 100,
    allowedRegions: ['swamp'],
    hostileFactions: ['联合帝国', '神圣教国'],
  },
  {
    id: 'holy_commoner',
    title: '圣民',
    description:
      '神圣教国的普通圣民，只要你向奥克兰以及他的祭司表示尊敬，你就能活得相对安全，神圣教国作为希望之地，坐拥肥沃的土壤、水源和资源，但日复一日的生活让你感到无趣，你想出去闯一闯，外面的世界据说非常野蛮暴力并且满是巨大丑陋的怪物。',
    difficulty: '普通',
    icon: 'Sun',
    equipment: ['《圣火》(书籍)', '防身小刀', '简单的布衣布裤'],
    money: 1500,
    allowedRegions: ['holy_nation', 'okan_bay'],
    allowedRaces: ['human'],
    allowedSubraces: ['greenlander', 'keter_descendant', 'scorchlander'],
    alliedFactions: ['神圣教国'],
    hostileFactions: ['联合帝国'],
  },
  {
    id: 'rock_bottom',
    title: '人生谷底',
    description:
      '你在沙漠中醒来。你失去了一只手臂，饥肠辘辘，身无分文。活下去。特质：失去左手。初始属性修正：力量-10、敏捷-10、感知-10、体质-10、智力-10、魅力-10。',
    difficulty: '极难',
    icon: 'Skull',
    equipment: ['无'],
    money: 0,
    allowedRegions: ['great_desert'],
  },
  {
    id: 'dark_daughter',
    title: '黑暗之女',
    description:
      '你是被诅咒的女孩，你们一族对于性爱的渴望超乎常人，你们的体液就是最好的催情剂，但也因此被圣骑士们赶尽杀绝，躲在了这一片污秽、不洁的黑暗之地，但是你降世了，你可以拯救这一种族，夺回荣光远胜此地百倍的故乡。',
    difficulty: '困难',
    icon: 'Moon',
    equipment: ['武士刀', '黑色亚麻衣物'],
    money: 1000,
    allowedRegions: ['iron_valley'],
    allowedRaces: ['narko'],
    allowedSubraces: ['narko_child'],
    allowedGenders: ['female'],
    alliedFactions: ['娜尔可'],
    hostileFactions: ['神圣教国'],
  },
  {
    id: 'officer_son',
    title: '贵族之子',
    description:
      '你的父亲是联合帝国军队内一位受人尊敬的长官。他在行动中被杀了，在你寻找工作的微薄积蓄被烧之后，你发现自己身无分文且饥肠辘辘，除了你父亲可信赖的刀和你背上的衬衫之外别无他物。联合帝国邦仍然是你的盟友。',
    difficulty: '普通',
    icon: 'Crown',
    equipment: ['长官佩刀', '衬衫'],
    money: 0,
    allowedRegions: ['great_desert', 'heng'],
    hostileFactions: ['神圣教国'],
    alliedFactions: ['联合帝国'],
  },
  {
    id: 'slave',
    title: '重生',
    description:
      '你只是另一个奴隶，在神圣教国重生镇的坑中工作，以建造一个毫无意义的雕像，你梦想着传说中的南方自由土地，并听说了北方叛乱分子的故事。',
    difficulty: '困难',
    icon: 'Pickaxe',
    equipment: ['破布衫'],
    money: 0,
    allowedRegions: ['rebirth'],
    hostileFactions: ['神圣教国'],
  },
  {
    id: 'male_slave',
    title: '男奴',
    description:
      '你曾是一个风光的科技猎手，一次冒险中，误入了她们的帝国，说了对女性不忠的话，现在你只是一条狗，要听话哦~',
    difficulty: '困难',
    icon: 'VenetianMask',
    equipment: ['破布衫'],
    money: 0,
    allowedRegions: ['south_wetlands'],
    fixedRegion: 'south_wetlands',
    fixedTown: '斯威士之剑',
    allowedGenders: ['male'],
    forbiddenRaces: ['skeleton'],
    hostileFactions: ['斯威士国'],
  },
  {
    id: 'cannibal_hunter',
    title: '食人族猎人',
    description: '“我真的很后悔来到了食人族的领地。这是个愚蠢的想法。”',
    difficulty: '极难',
    icon: 'Skull',
    equipment: ['砍刀', '高级急救包 x1'],
    money: 200,
    allowedRegions: ['cannibal_plains'],
    hostileFactions: ['食人族部落'],
  },
  {
    id: 'pirate_heir',
    title: '海盗之梦',
    description:
      '你早早听说了海盗王的风光故事，你大老远来到此处就是为了学习如何成为一名强大海盗，协助海盗王或是夺取他的名号，在这片大陆中名垂千古。',
    difficulty: '困难',
    icon: 'Skull',
    equipment: ['弯刀', '破旧披风'],
    money: 300,
    allowedRegions: ['green_coast'],
  },
  {
    id: 'cannibal_unifier',
    title: '呜哇呜哇哇(夺回家园)',
    description:
      '你是肉主部落的一族，南方的食人族猎手杀死了你的家人，你只是想活下去，有什么错。杀光他们，将他们的头颅挂在你的旗子上，让世人皆知你的名号。',
    difficulty: '极难',
    icon: 'Skull',
    equipment: ['巨骨战斧', '兽皮披肩', '干肉'],
    money: 0,
    allowedRegions: ['dark_finger'],
    allowedRaces: ['cannibal'],
    alliedFactions: ['肉主部落'],
    hostileFactions: ['大巫部落', '食人族猎手'],
  },
  {
    id: 'brotherhood_prisoner',
    title: '兄弟会',
    description:
      '你是愿意当个无名之辈，一辈子被踩在脚下，然后像条野狗一样死在路边?还是愿意拿起刀，就算活不到三十岁也要让所有贵族都记住你的名字！！！',
    difficulty: '困难',
    icon: 'Pickaxe',
    equipment: [],
    money: 0,
    allowedRegions: ['stobers_garden'],
    alliedFactions: ['鲜血掠夺者'],
    hostileFactions: ['联合帝国'],
  },
  {
    id: 'freedom_seekers',
    title: '无名之辈(测试版，可能存在bug',
    description:
      '你厌倦了令人窒息的城市生活和税收，你集结了一个小队外出并找到了自己的家园基地。你已经组建了一个加上你一共五个志同道合的人组成的团队，并且已经收集了大量的建筑材料。',
    difficulty: '普通',
    icon: 'Users',
    equipment: ['铁棒 x3', '基础医疗包', '建筑材料'],
    money: 2000,
  },
  {
    id: 'mongrel_wanderer',
    title: '蒙格勒迷途者',
    description: '浓雾笼罩的雾岛之中，你在迷途中求生，依靠残存的意志寻找出路。',
    difficulty: '困难',
    icon: 'Compass',
    equipment: ['破旧披风', '干粮'],
    money: 200,
    allowedRegions: ['fog_islands'],
  },
  {
    id: 'merchant',
    title: '流浪商人',
    description: '你有一些积蓄和一头驮兽。你渴望在这个残酷的世界中建立一个贸易帝国。',
    difficulty: '简单',
    icon: 'Coins',
    equipment: ['商人的背包', '铁棒', '驼牛'],
    money: 4000,
    companions: [
      {
        race: 'pack_beast',
        subrace: 'pack_beast',
        level: 1,
        attributes: {
          strength: 1,
          dexterity: 1,
          perception: 1,
          constitution: 1,
          will: 1,
          intelligence: 1,
          charisma: 1,
        },
        name: '驼兽',
        gender: 'other',
        age: 6,
        appearance: {
          eyes: '',
          hairStyle: '',
          hairColor: '',
          bodyType: '',
          height: 190,
          description: '',
        },
        traits: [],
        customTraitName: '',
        customTraitDescription: '',
      },
    ],
  },
  {
    id: 'kral_choice',
    title: '克拉尔之选',
    description:
      '有人说你是克拉尔的后裔，沙克王国传说中的勇士，你应当是沙克王国的合法首领，你已经准备好在历史上占据一席之地。懦弱的女皇坐在沙克王国的宝座上瑟瑟发抖，她唯一的计划就是坐以待毙，等什么？难道要等奥克兰人向一个曾经骄傲的王国发动毁灭的入侵？沙克人需要一个强有力的领导，而你就是将团结沙克族的人！！拯救我们的种族！！复兴我们的王国！！！！',
    difficulty: '困难',
    icon: 'Crown',
    equipment: ['沙克大剑', '破烂的雇佣兵之甲'],
    money: 0,
    allowedRegions: ['stenn_desert'],
    allowedRaces: ['shek'],
    allowedSubraces: ['shek_royal'],
    alliedFactions: ['克拉尔之选'],
    hostileFactions: ['沙克王国'],
  },
  {
    id: 'fish_island_refugee',
    title: '渔岛难民',
    description:
      '你是受鱼形人危机影响的难民。你不确定你的生活会变成什么样。也许你最好把这一切抛在脑后…或者继续和这些野兽战斗。',
    difficulty: '普通',
    icon: 'Fish',
    equipment: ['鱼矛', '雇佣兵之甲'],
    money: 500,
    allowedRegions: ['bonefields_south'],
    allowedRaces: ['lizardfolk'],
    alliedFactions: ['库尔林'],
    hostileFactions: ['鱼形人'],
  },
  {
    id: 'bast_stray',
    title: '带着狗的家伙',
    description:
      '联合帝国和神圣教国之间的战争使这个曾经繁荣的地区变得荒凉、破败、贫穷和贫瘠。你是一个无家可归、饥肠辘辘的漂泊者，救了一只被遗弃的小狗，它似乎非常没用，也许你只会吃了它。尝试面对北方食人族的袭击、西方神圣教国的行刑队以及渴望用极端偏见解决任何难民问题的南方联合城武士巡逻队生存下来，你听说了一些大沙漠北方叛乱分子的传言……',
    difficulty: '困难',
    icon: 'PawPrint',
    equipment: ['破布衫'],
    money: 500,
    allowedRegions: ['bast'],
    fixedRegion: 'bast',
    fixedTown: '巴斯特城',
    companions: [
      {
        race: 'canine',
        subrace: 'stray_dog',
        level: 1,
        attributes: {
          strength: 1,
          dexterity: 1,
          perception: 1,
          constitution: 1,
          will: 1,
          intelligence: 1,
          charisma: 1,
        },
        name: '小狗',
        gender: 'other',
        age: 1,
        appearance: {
          eyes: '',
          hairStyle: '',
          hairColor: '',
          bodyType: '',
          height: 50,
          description: '',
        },
        traits: [],
        customTraitName: '',
        customTraitDescription: '',
      },
    ],
  },
  {
    id: 'author_self_test',
    title: '作者自测用',
    description: '仅用于作者内部自测的隐藏剧本。',
    difficulty: '普通',
    icon: 'Eye',
    equipment: ['无'],
    money: 0,
    hidden: true,
  },
];

export const REGIONS = [
  {
    id: 'leviathan_coast',
    title: '利维坦海岸',
    description:
      '大陆西北角的辽阔滨海平原，紫色土壤与稀疏的紫林一路延展至发黑礁岸。地势开阔、水源充沛，巨型生物在此游弋繁衍，令整片海岸成为狩猎者与猎物共同的乐园。',
    towns: ['利维坦观测站'],
    danger: '极高',
  },
  {
    id: 'iron_valley',
    title: '铁之谷',
    description: '污秽与黑暗盘踞之地，娜尔可一族在此隐藏，等待复兴的火种。',
    towns: ['娜尔可守望'],
    danger: '极高',
  },
  {
    id: 'stenn_desert',
    title: '斯坦沙漠',
    description: '沙克王国的广袤沙海，强者与荣耀的试炼之地。',
    towns: ['新卡拉迪亚'],
    danger: '高',
  },
  {
    id: 'bonefields_south',
    title: '骸骨荒原南部',
    description: '荒原南部的腐骨与盐风交织，渔网散落在海风与尘沙之间。',
    towns: ['渔网'],
    danger: '高',
  },
  {
    id: 'stobers_garden',
    title: '斯托伯的花园',
    description: '被遗忘的残垣与荒草蔓延，古代残迹在此沉眠。',
    towns: ['方舟'],
    danger: '极高',
  },
  {
    id: 'eye_land',
    title: '目之地',
    description:
      '风沙永不停歇的荒芜沙海。传说一颗古老卫星曾坠毁于此，破碎残骸深埋地底，至今仍扰动着整片地域的气流与磁场，让沙暴终年不息。',
    towns: ['沙尔维尔驿站'],
    danger: '极高',
  },
  {
    id: 'border_zone',
    title: '边境之地',
    description: '神圣王国与沙克王国之间的缓冲地带。这里是流浪者、强盗和被流放者的家园。',
    towns: ['枢纽城', '斯昆镇'],
    danger: '中等',
  },
  {
    id: 'great_desert',
    title: '大沙漠',
    description: '联合城的中心地带。这里有巨大的财富，也有残酷的奴隶制。',
    towns: ['赫夫特城', '小巴泰镇', '白鼬镇', '巴克镇'],
    danger: '高',
  },
  {
    id: 'heng',
    title: '恒',
    description: '充满铜臭与野心的白色沙海。希望你带来了足够多的金钱。',
    towns: ['恒城', '汉城', '元城'],
    danger: '高',
  },
  {
    id: 'holy_nation',
    title: '奥克兰之傲',
    description: '肥沃的绿地，由狂热的宗教统治。如果你是人类男性，这里是天堂；否则，这里是地狱。',
    towns: ['水泡山丘', '坏牙镇', '恩勒门特'],
    danger: '极高 (对非人类)',
  },
  {
    id: 'okan_bay',
    title: '奥克兰之湾',
    description: '圣国北部沿海的冷峻湾区，险峻峭壁与严苛教规并存，圣火在海风中更显肃穆。',
    towns: ['斯塔克镇'],
    danger: '高',
  },
  {
    id: 'bast',
    title: '巴斯特',
    description: '联合帝国与神圣教国之间的战火撕裂了这片土地，曾经繁荣的聚落如今荒凉、破败、贫穷而贫瘠。',
    towns: ['巴斯特城'],
    danger: '高',
  },
  {
    id: 'swamp',
    title: '沼泽地',
    description: '无法无天的地带，充满了走私犯、帮派和致命的生物。',
    towns: ['鲨鱼城'],
    danger: '中等',
  },
  {
    id: 'cannibal_plains',
    title: '食人族平原',
    description: '狂乱野蛮之地，遍布饥饿的食人族。只有不停奔跑，才能免于被生吞活剥。',
    towns: ['死猫村之都'],
    danger: '极高',
  },
  {
    id: 'dark_finger',
    title: '黑暗之指',
    description: '这里主要栖息着作为土著的食人部落，是联合帝国北部的一大威胁区域。',
    towns: ['野外'],
    danger: '极高',
  },
  {
    id: 'green_coast',
    title: '绿色海岸',
    description: '危险而肥沃的土地。若想在此立足，你最好先向那群怪人或是巨蟹证明忠诚。',
    towns: ['托尔图加'],
    danger: '高',
  },
  {
    id: 'rebirth',
    title: '重生镇',
    description: '建立在岩石上的地狱。奴隶们通过无止境的劳作，试图洗刷那虚无缥缈的罪孽。',
    towns: ['重生镇'],
    danger: '极高',
  },
  {
    id: 'fog_islands',
    title: '雾岛',
    description: '浓雾笼罩的哀嚎之谷。我看不见它们，它们却能找到我。',
    towns: ['蒙格勒'],
    danger: '极高',
  },
  {
    id: 'south_wetlands',
    title: '钩子海滨',
    description: '联合城与商会掌控的繁荣海滨。财富流动之余，女权主义的极端势力在此割据。',
    towns: ['漂泊终地', '斯威士之剑', '吉利之剑', '科隆斯城'],
    danger: '高',
  },
  {
    id: 'bonefields',
    title: '骸骨荒原',
    description: '遍布远古巨兽骸骨的荒原。成群的长颈鹿在此游荡，将闯入者吞入腹中。',
    towns: ['开顿城'],
    danger: '极高',
  },
];

export const TOWN_DESCRIPTIONS: Record<string, string> = {
  枢纽城: '战火后残破的旧枢纽，废墟之上仍有人企图重建。',
  斯昆镇: '峡谷深处的石墙城塞，守望着通往荒原的险隘。',
  赫夫特城: '联合城的煌煌首都，权势与金银在此交织成网。',
  小巴泰镇: '大沙漠腹地的商旅据点，尘沙中维系着帝国脉络。',
  白鼬镇: '沙海贸易之心，驼队与商队在此汇流不息。',
  巴克镇: '帝国唯一的沿海大城，通往岛都的命脉港口。',
  恒城: '商人行会的繁荣都市，财富在白沙上闪耀。',
  汉城: '华奢堪比帝都的欢愉之地，欲望与奢侈永不止息。',
  元城: '汉城背后的破败村落，在辉煌阴影下苟延。',
  水泡山丘: '圣国信仰中心的繁荣首都，圣火与秩序在此高悬。',
  坏牙镇: '山谷间的边境之镇，兵刃与风尘并存。',
  斯塔克镇: '背靠峻岭的城镇，天险如墙，铁律如钢。',
  恩勒门特: '圣国的大教堂城镇，钟声昼夜回响，信徒与圣骑士在此守望圣火。',
  巴斯特城: '战争夹缝中的残破城镇，难民与巡逻队在此周旋。',
  鲨鱼城: '沼泽地的中心之城，大麻与金钱的交易随处可见。',
  托尔图加: '海盗们如今的家园，巨大的海盗船在此搁浅。',
  重生镇: '罪人重生之地，苦役与忏悔在石壁间回响。',
  蒙格勒: '环绕迷雾之心而建的城邦，罪人最后的庇护所。',
  漂泊终地: '帝国西南角的奴隶城，铁链铸成此地的律法。',
  斯威士之剑: '女儿国的首都，权势与锋芒在此并立。',
  吉利之剑: '商人行会西南角的贸易城，金流与契约铺路。',
  科隆斯城: '无贵族的联合之城，自由与秩序在此角力。',
  开顿城: '高地上的联合之城，四周遍布巨兽骸骨。',
  沙尔维尔驿站: '矗立于目之地风暴腹地的孤独旅馆，商旅、逃亡者与濒死之人都曾在此歇脚。',
  利维坦观测站: '营地位于海岸高地，瞭望塔与简易帐篷拼接而成，是追踪巨兽动向的前线据点。',
};

export const RACES = [
  {
    id: 'human',
    title: '人类',
    description:
      '人类是废土上数量最多、分布最广的种族，其生理结构最为标准和均衡。他们没有坚硬的骨板或厚实的甲壳，肉体相对脆弱，且对废土上恶劣的自然环境没有任何天生的抵抗力。不过，人类的优势在于其无与伦比的学习能力，他们是适应性最强的种族，没有明显的短板，但也没有突出的优势。',
    subraces: [
      {
        id: 'greenlander',
        title: '绿原之子',
        description:
          '作为人类中最庞大且最具代表性的群体，绿原之子是废土上绝大多数文明体系的缔造者与基石。他们生来就习惯于在复杂的社会与体制中生存，拥有极高的农业、烹饪和科学天赋。平庸的体质可能会让他们吃尽苦头，但凭借无与伦比的适应能力，他们往往能迅速学会新的生存技能，甚至在荒野中建立起属于自己的新家园。',
        attributeSummary: '智力+10',
      },
      {
        id: 'scorchlander',
        title: '焦土之子',
        description:
          '焦土之子是天生的叛逆者和冒险家。他们拥有深色的肌肤，生性桀骜不驯，极度厌恶枯燥的农业劳动与任何形式的社会约束。他们崇尚绝对的个体自由，行事往往随心所欲，因此不愿在等级森严的帝国中安分守己。正因如此，部分派系厌恶并且鄙视这一肤色的种族，视其为劣等人类。',
        attributeSummary: '敏捷+5、魅力-5',
      },
      {
        id: 'keter_descendant',
        title: '奇特林后裔',
        description:
          '奇特林后裔传闻是奥克兰血脉，他们生来就缺乏任何道德与信仰的寄托，终生被无尽的贪婪与极度的恐惧所支配，对这片残酷大陆上的所有生命都抱有病态的猜疑。因为内心的极度缺乏安全感，他们几乎本能地诉诸野蛮的暴力，将其作为生存、掠夺和掩饰软弱的唯一手段。',
        attributeSummary: '感知+10、智力-10',
      },
    ],
  },
  {
    id: 'narko',
    title: '娜尔可',
    description: '被诅咒的一族，你们肤色惨白，但却出奇的美丽，对于性爱的疯狂追求使得你们遭人唾弃。',
    subraces: [
      {
        id: 'narko_child',
        title: '蒙受神恩者',
        description:
          '蒙受神恩者又称为堕落者，或者魅魔。尽管外表与人类相似，但经研究，她们的身体内部结构和人类截然不同。甚至说，更加接近被称为骨人的物种。而在他们尚未变化，还属于人类族类之时，和人类一样属于肉身。她们身体的这种改变，和古代人类有关。。。。。甚至是发生了变异。',
        attributeSummary: '敏捷+5、魅力+15、力量-5、体质-10',
      },
    ],
  },
  {
    id: 'west_hive',
    title: '西部蜂巢族',
    description:
      '蜂巢族拥有近似昆虫的生理结构，最显著的特征是极其细长、宛如枯枝般的四肢。他们的身体异常脆弱，四肢很容易在战斗中被切断。他们的胸腔骨骼奇特，导致无法穿戴普通人类的衬衫；由于生有极其宽大、平坦且没有脚趾的脚掌，他们终生无法穿戴任何鞋类。不过，他们体内流淌着特殊的体液，天生免疫废土上致命的酸雨。\n\n善于经商的黄色皮肤蜂巢族，是废土上最友善的一群人。\n初始属性修正：魅力+10、敏捷+5、力量-10。\n技能加成：交易+15、说服+5。\n种族特性：商业头脑。\n西部蜂巢族是善于经商的黄色皮肤蜂巢族，是大陆上最友善但贪婪的一群人。',
    subraces: [
      {
        id: 'hive_prince',
        title: '智蜂',
        description:
          '蜂巢中的最高等级，女王的右手。没有人见过真正的女王，是智蜂掌管一切。自由智蜂通常是由于失去对一位敌对智蜂的命令，或是被驱逐出去作为对某种失败的惩罚而导致的结果。它们比普通的蜂群更聪明，更自由。',
        attributeSummary: '智力+15、感知+10、力量-10',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_worker',
        title: '工蜂',
        description:
          '这些工人是消耗品，生来就是为蜂巢劳动的，他们只知道服从和为蜂巢族服务，他们将这些置于个人利益、安危和舒适之上。如果切断蜂巢对他们的控制，他们通常就会死亡，但在极少数情况下也会成为自由的个体。他们会对新得到的自由感到困惑，也会因为失去预先确定的目的而迷茫，他们会茫然地寻找人生的意义，但他们通常只能找到死亡和剥削。',
        attributeSummary: '敏捷+5、力量+5、体质+5、智力-15',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_soldier',
        title: '兵蜂',
        description:
          '兵蜂生来就是为了保护蜂巢和控制工蜂。他们比工蜂更强壮，也更聪明，他们很少追寻自由，脱离种族的人最后大多成为了雇佣兵或是其他派系的士兵。',
        attributeSummary: '智力+15、感知+10、力量-10、敏捷+5',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_princess',
        title: '蜂巢公主',
        description:
          '每隔一段时间，就有一种异常体出现在蜂巢族的形成过程中。古老的基因模板，长时间处于休眠状态，干扰并与标准工蜂融合在一起。大多数情况下，这导致了可恶的动物的死亡，但偶尔也会有一个幸存下来。一个假女王，注定要制造失败的蜂房，然后慢慢地腐烂。由于它们无法自己创造新的蜂巢族，而且通常没有信息素来保持它们的温顺和顺从，它们很快就会被赶出蜂巢，在严酷的外部世界中枯萎。',
        attributeSummary: '魅力+5、敏捷+5、感知+5、力量-15',
        allowedGenders: ['female'],
      },
    ],
  },
  {
    id: 'south_hive',
    title: '南部蜂巢族',
    description:
      '蜂巢族拥有近似昆虫的生理结构，最显著的特征是极其细长、宛如枯枝般的四肢。他们的身体异常脆弱，四肢很容易在战斗中被切断。他们的胸腔骨骼奇特，导致无法穿戴普通人类的衬衫；由于生有极其宽大、平坦且没有脚趾的脚掌，他们终生无法穿戴任何鞋类。不过，他们体内流淌着特殊的体液，天生免疫废土上致命的酸雨。\n\n极度排外且侵略性的血红色蜂巢族，拥有更强的军事力量。\n初始属性修正：力量+5、体质+5、魅力-15、智力-10。\n种族特性：战斗狂热（最终伤害+5）。\n南部蜂巢族极度排外且侵略性的血红色肤色的蜂巢族，拥有更强的军事力量但智力其他相比较低',
    subraces: [
      {
        id: 'hive_prince',
        title: '智蜂',
        description:
          '蜂巢中的最高等级，女王的右手。没有人见过真正的女王，是智蜂掌管一切。自由智蜂通常是由于失去对一位敌对智蜂的命令，或是被驱逐出去作为对某种失败的惩罚而导致的结果。它们比普通的蜂群更聪明，更自由。',
        attributeSummary: '智力+15、感知+10、力量-10',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_worker',
        title: '工蜂',
        description:
          '这些工人是消耗品，生来就是为蜂巢劳动的，他们只知道服从和为蜂巢族服务，他们将这些置于个人利益、安危和舒适之上。如果切断蜂巢对他们的控制，他们通常就会死亡，但在极少数情况下也会成为自由的个体。他们会对新得到的自由感到困惑，也会因为失去预先确定的目的而迷茫，他们会茫然地寻找人生的意义，但他们通常只能找到死亡和剥削。',
        attributeSummary: '敏捷+5、力量+5、体质+5、智力-15',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_soldier',
        title: '兵蜂',
        description:
          '兵蜂生来就是为了保护蜂巢和控制工蜂。他们比工蜂更强壮，也更聪明，他们很少追寻自由，脱离种族的人最后大多成为了雇佣兵或是其他派系的士兵。',
        attributeSummary: '智力+15、感知+10、力量-10、敏捷+5',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_princess',
        title: '蜂巢公主',
        description:
          '每隔一段时间，就有一种异常体出现在蜂巢族的形成过程中。古老的基因模板，长时间处于休眠状态，干扰并与标准工蜂融合在一起。大多数情况下，这导致了可恶的动物的死亡，但偶尔也会有一个幸存下来。一个假女王，注定要制造失败的蜂房，然后慢慢地腐烂。由于它们无法自己创造新的蜂巢族，而且通常没有信息素来保持它们的温顺和顺从，它们很快就会被赶出蜂巢，在严酷的外部世界中枯萎。',
        attributeSummary: '魅力+5、敏捷+5、感知+5、力量-15',
        allowedGenders: ['female'],
      },
    ],
  },
  {
    id: 'dark_hive',
    title: '黑暗蜂巢族',
    description:
      '蜂巢族拥有近似昆虫的生理结构，最显著的特征是极其细长、宛如枯枝般的四肢。他们的身体异常脆弱，四肢很容易在战斗中被切断。他们的胸腔骨骼奇特，导致无法穿戴普通人类的衬衫；由于生有极其宽大、平坦且没有脚趾的脚掌，他们终生无法穿戴任何鞋类。不过，他们体内流淌着特殊的体液，天生免疫废土上致命的酸雨。\n\n罕见的黑色皮肤蜂巢族，拥有更高智商与均衡实力。\n初始属性修正：智力+10、力量+5、敏捷+5、体质-5。\n种族特性：古老基因（可无惩罚使用所有武器）。\n黑暗蜂巢族是罕见的黑色皮肤蜂巢族，拥有更高智商与均衡实力，但是他们一族因为女王的特殊性，数量相比较为稀少',
    subraces: [
      {
        id: 'hive_prince',
        title: '智蜂',
        description:
          '蜂巢中的最高等级，女王的右手。没有人见过真正的女王，是智蜂掌管一切。自由智蜂通常是由于失去对一位敌对智蜂的命令，或是被驱逐出去作为对某种失败的惩罚而导致的结果。它们比普通的蜂群更聪明，更自由。',
        attributeSummary: '智力+15、感知+10、力量-10',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_worker',
        title: '工蜂',
        description:
          '这些工人是消耗品，生来就是为蜂巢劳动的，他们只知道服从和为蜂巢族服务，他们将这些置于个人利益、安危和舒适之上。如果切断蜂巢对他们的控制，他们通常就会死亡，但在极少数情况下也会成为自由的个体。他们会对新得到的自由感到困惑，也会因为失去预先确定的目的而迷茫，他们会茫然地寻找人生的意义，但他们通常只能找到死亡和剥削。',
        attributeSummary: '敏捷+5、力量+5、体质+5、智力-15',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_soldier',
        title: '兵蜂',
        description:
          '兵蜂生来就是为了保护蜂巢和控制工蜂。他们比工蜂更强壮，也更聪明，他们很少追寻自由，脱离种族的人最后大多成为了雇佣兵或是其他派系的士兵。',
        attributeSummary: '智力+15、感知+10、力量-10、敏捷+5',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_princess',
        title: '蜂巢公主',
        description:
          '每隔一段时间，就有一种异常体出现在蜂巢族的形成过程中。古老的基因模板，长时间处于休眠状态，干扰并与标准工蜂融合在一起。大多数情况下，这导致了可恶的动物的死亡，但偶尔也会有一个幸存下来。一个假女王，注定要制造失败的蜂房，然后慢慢地腐烂。由于它们无法自己创造新的蜂巢族，而且通常没有信息素来保持它们的温顺和顺从，它们很快就会被赶出蜂巢，在严酷的外部世界中枯萎。',
        attributeSummary: '魅力+5、敏捷+5、感知+5、力量-15',
        allowedGenders: ['female'],
      },
    ],
  },
  {
    id: 'shek',
    title: '沙克族',
    description:
      '沙克族是一个纯粹为战斗而生的种族。他们的生理结构异常粗犷强壮，最显著的特征是全身覆盖着天然的骨板，以及头部锋利的骨角。这些骨骼装甲为他们提供了极强的抗击打能力，使他们的身体远比人类和蜂巢族坚韧，但也因此他们没有毛发。骨角被认为是沙克族无上荣耀的象征，一旦在战斗中退缩或因犯罪被强行锯除，便会被全族唾弃，沦为耻辱的“无角者”。强大的肌肉密度导致他们新陈代谢极快，食量十分惊人。',
    subraces: [
      {
        id: 'shek_warrior',
        title: '沙克战士',
        description:
          '这是一个战士社会，重视力量与勇气胜过智慧，他们有时会缺乏幽默感，被认为是愚蠢的野兽，但并不总是这样，他们的外骨骼是一种天然的铠甲，但也妨碍了他们进行灵巧的活动，比如偷偷摸摸做事。',
        attributeSummary: '力量+10、体质+10、敏捷-10、智力-10',
      },
      {
        id: 'shek_royal',
        title: '沙克皇族',
        description:
          '沙克皇族是沙克族中一个最强大的上位种族，他们更为健壮与智慧，但是十分少见，只能在沙克王国内见到，是正统的沙克血脉。',
        attributeSummary: '力量+15、体质+15、敏捷-5',
        locked: true,
        lockedReason: '仅“克拉尔之选”剧本可选',
        unlockScenarios: ['kral_choice'],
      },
    ],
  },
  {
    id: 'lizardfolk',
    title: '原始种族',
    description: '由更古老的血脉衍生的原始种族分支。',
    subraces: [
      {
        id: 'lizardfolk_base',
        title: '蜥蜴人',
        description:
          '蜥蜴人是潜伏在大陆上强壮的爬行类战士，最显著的特征是全身覆盖着一层坚韧且排列致密的鳞片皮肤。这些鳞片如同天然的盔甲，为他们提供了极佳的额外保护。作为可怕的猎手，他们拥有锐利的尖牙与利爪；但由于长有反关节的爬行类下肢与巨大的趾爪，他们与蜂巢族一样终生无法穿戴任何鞋类，粗壮的尾巴和修长的吻部也使得他们难以戴上普通人类的全封闭头盔。不过，尽管有这种爬行动物看起来十分具有威胁，但在这个大陆的生存上还是比较失败的，许多人猎杀他们并剥下他们的鳞片进行售卖制作。',
        attributeSummary: '体质+5、敏捷+10、感知+5、魅力-15',
      },
      {
        id: 'goatfolk',
        title: '山羊人',
        description: '尚未完善背景设定。',
        locked: true,
        lockedReason: '作者暂未做完背景',
        unlockScenarios: ['author_self_test'],
      },
      {
        id: 'fungoid',
        title: '真菌人',
        description: '尚未完善背景设定。',
        locked: true,
        lockedReason: '作者暂未做完背景',
        unlockScenarios: ['author_self_test'],
      },
      {
        id: 'fishfolk',
        title: '鱼形人',
        description: '拥有水生特征的古老血脉。',
        locked: true,
        lockedReason: '作者暂未做完背景',
        unlockScenarios: ['author_self_test'],
      },
    ],
  },
  {
    id: 'cannibal',
    title: '食人族',
    description:
      '食人族天性野蛮，而且经常会相互争斗，他们还会吃同类的身体。但据可靠消息，他们曾经也是人类，似乎第二帝国的一些原因，使得大脑出了问题，并且饥饿使得他们同类相食。他们有着自己的语言沟通，因为饥饿导致他们大部分人营养不良，智力低下。',
    subraces: [
      {
        id: 'cannibal_brute',
        title: '食人族大只佬',
        description: '粗野巨躯的大型食人族，他的大脑相对于其他亚种更为愚蠢。初始属性修正：体质+20、智力-35、感知-15。',
      },
      {
        id: 'cannibal_warrior',
        title: '干瘦食人族',
        description: '体态干瘦却动作迅猛的的他们，一般属于食人族中的炮灰。初始属性修正：敏捷+15、智力-20、体质-10。',
      },
      {
        id: 'cannibal_priest',
        title: '食人族祭师',
        description: '食人族中最为聪明的存在，至少他们会讲人类的语言。初始属性修正：智力+15、体质-15。',
      },
    ],
  },
  {
    id: 'skeleton',
    title: '骨人',
    description:
      '骨人完全是个谜，没人知道他们来自哪里，又是怎么被创造出来的，但人们认为他们已经有几千岁了。他们有完整的感情，能感到悲伤，愤怒，激动，同情，震惊和快乐，但他们不能通过表情展示出来，再加上他们缺乏幽默感，总是让其他种族感到困惑，比如沙克族就认为他们善变，难以预料。他们没有偏见，无惧死亡，因此是勇敢无畏的战士。种族特质：无情面容（魅力表情检定失败但免疫恐惧）。',
    subraces: [
      {
        id: 'skeleton_mki',
        title: 'MKI (圆头)',
        description: '初始属性修正：体质+5。',
      },
      {
        id: 'skeleton_mkii',
        title: 'MKII (摄像头)',
        description: '初始属性修正：感知+5。',
      },
      {
        id: 'skeleton_mkiii',
        title: 'MKIII (尖头)',
        description: '初始属性修正：力量+5。',
      },
    ],
  },
  {
    id: 'canine',
    title: '犬类',
    description: '废土上常见的流浪犬族群，多以本能和饥饿驱动。',
    hidden: true,
    subraces: [
      {
        id: 'stray_dog',
        title: '流浪犬',
        description: '饥肠辘辘的小型犬类，敏感而谨慎。',
      },
    ],
  },
  {
    id: 'pack_beast',
    title: '驼兽',
    description: '商队常用的负重兽类，性情温驯而耐力惊人。',
    hidden: true,
    subraces: [
      {
        id: 'pack_beast',
        title: '驼兽',
        description: '常见的驮兽品种，可在恶劣环境中长途跋涉。',
      },
    ],
  },
];

export const TRAITS = {
  attribute: [
    {
      id: 'tough',
      title: '坚韧',
      description: '你的皮肤像皮革一样粗糙。体质 +5',
      category: 'attribute',
    },
    {
      id: 'iron_bones',
      title: '铁骨',
      description: '骨骼如铁。力量 +5',
      category: 'attribute',
    },
    {
      id: 'swift',
      title: '迅捷',
      description: '步伐轻快如风。敏捷 +5',
      category: 'attribute',
    },
    {
      id: 'hawk_eye',
      title: '鹰眼',
      description: '视线锐利无比。感知 +5',
      category: 'attribute',
    },
    {
      id: 'strategist',
      title: '谋略家',
      description: '思路清晰，擅长筹划。智力 +5',
      category: 'attribute',
    },
    {
      id: 'unyielding',
      title: '不屈',
      description: '意志像钢铁般坚定。意志 +5',
      category: 'attribute',
    },
    {
      id: 'silver_tongue',
      title: '巧言',
      description: '言辞得体，善于交涉。魅力 +5',
      category: 'attribute',
    },
    {
      id: 'thief',
      title: '惯偷',
      description: '手指灵活，动作干净利落。敏捷 +5',
      category: 'attribute',
    },
    {
      id: 'laborer',
      title: '苦工',
      description: '久经体力劳作。力量 +5',
      category: 'attribute',
    },
    {
      id: 'endurant',
      title: '耐性',
      description: '经得起疲惫与饥饿。体质 +5',
      category: 'attribute',
    },
    {
      id: 'alert',
      title: '警觉',
      description: '对周围的变化极其敏感。感知 +5',
      category: 'attribute',
    },
    {
      id: 'intuitive',
      title: '直觉',
      description: '对局势的判断更快。智力 +5',
      category: 'attribute',
    },
  ],
  life: [
    {
      id: 'glutton',
      title: '暴食者',
      description: '你更容易感到饥饿。',
      category: 'life',
    },
    {
      id: 'insomniac',
      title: '失眠者',
      description: '你总是难以入睡。',
      category: 'life',
    },
    {
      id: 'greedy',
      title: '贪婪',
      description: '你对财富有强烈执念。',
      category: 'life',
    },
    {
      id: 'soft_hearted',
      title: '心软',
      description: '你难以拒绝别人的请求。',
      category: 'life',
    },
    {
      id: 'loner',
      title: '独行者',
      description: '你更习惯独自行动。',
      category: 'life',
    },
    {
      id: 'impulsive',
      title: '冲动',
      description: '你经常先行动后思考。',
      category: 'life',
    },
    {
      id: 'paranoid',
      title: '多疑',
      description: '你很难完全信任他人。',
      category: 'life',
    },
    {
      id: 'dreamer',
      title: '空想家',
      description: '你常沉浸在幻想里。',
      category: 'life',
    },
    {
      id: 'stingy',
      title: '吝啬',
      description: '你不愿轻易花费资源。',
      category: 'life',
    },
    {
      id: 'messy',
      title: '邋遢',
      description: '你不太在意整洁。',
      category: 'life',
    },
  ],
  fun: [
    {
      id: 'goblin_mode',
      title: '小地精模式',
      description: '你会把废墟里的破烂当作宝藏。',
      category: 'fun',
    },
    {
      id: 'campfire_poet',
      title: '篝火诗人',
      description: '你喜欢在篝火旁吟诵尬诗。',
      category: 'fun',
    },
    {
      id: 'chaos_gremlin',
      title: '混乱小妖',
      description: '你总能把事态往奇怪方向推。',
      category: 'fun',
    },
    {
      id: 'meme_lord',
      title: '迷因之王',
      description: '你能在任何场合讲出烂梗。',
      category: 'fun',
    },
    {
      id: 'fourth_wall',
      title: '打破第四面墙',
      description: '你偶尔会盯着镜头说话。',
      category: 'fun',
    },
    {
      id: 'spicy_talker',
      title: '口无遮拦',
      description: '你说话经常跑偏。',
      category: 'fun',
    },
    {
      id: 'midnight_story',
      title: '午夜故事家',
      description: '你喜欢讲一些让人尴尬的故事。',
      category: 'fun',
    },
    {
      id: 'improper_thinker',
      title: '不正经的脑内剧场',
      description: '你总能把日常联想到奇怪的画面。',
      category: 'fun',
    },
  ],
};
