export const SCENARIOS = [
  {
    id: 'wanderer',
    title: '流浪者 (The Wanderer)',
    description: '你独自一人，身无分文，只有一把生锈的剑和背上的衣服。这是最纯粹的Kenshi体验。',
    difficulty: '普通',
    icon: 'Sword',
    equipment: ['生锈的铁剑', '破旧的裤子'],
    money: 1000,
  },
  {
    id: 'unknown_dream',
    title: '未知梦想',
    description: '你不被任何既定剧本束缚。自行决定来历、携带装备与开局物品，写下属于你的第一章。',
    difficulty: '普通',
    icon: 'Sparkles',
    equipment: ['无'],
    money: 0,
  },
  {
    id: 'slave_master',
    title: '奴隶主',
    description:
      '你生来就是联合帝国的上层贵族，财富、权势与奴仆唾手可得。如今你牵着两名私人奴隶踏入赫夫特城，表面风光无限，暗地里却已被反蓄奴者盯上。金钱能买来忠诚，也能买来仇恨——在刀锋与阴谋之间，守住你的地位。',
    difficulty: '困难',
    icon: 'Handcuffs',
    equipment: ['贵族服饰', '短刀', '奴隶镣铐钥匙'],
    money: 8000,
    fixedRegion: 'great_desert',
    fixedTown: '赫夫特城',
    alliedFactions: ['联合城', '商人行会', '奴隶商人'],
    hostileFactions: ['反蓄奴者'],
    companions: [
      {
        race: 'human',
        subrace: 'greenlander',
        level: 1,
        attributes: {
          strength: 12,
          dexterity: 12,
          perception: 10,
          constitution: 12,
          will: 10,
          intelligence: 8,
          charisma: 6,
        },
        name: '私人奴隶A',
        gender: 'male',
        age: 22,
        appearance: {
          eyes: '',
          hairStyle: '',
          hairColor: '',
          bodyType: '消瘦',
          height: 172,
          description: '骨瘦如柴，神情麻木，脖颈有明显镣铐磨痕。',
        },
        traits: [],
        customTraitName: '',
        customTraitDescription: '',
      },
      {
        race: 'human',
        subrace: 'scorchlander',
        level: 1,
        attributes: {
          strength: 10,
          dexterity: 13,
          perception: 10,
          constitution: 11,
          will: 10,
          intelligence: 8,
          charisma: 6,
        },
        name: '私人奴隶B',
        gender: 'female',
        age: 21,
        appearance: {
          eyes: '',
          hairStyle: '',
          hairColor: '',
          bodyType: '消瘦',
          height: 168,
          description: '长期营养不良，眼神空洞，行动谨慎而机械。',
        },
        traits: [],
        customTraitName: '',
        customTraitDescription: '',
      },
    ],
  },
  {
    id: 'human_torso',
    title: '人棍',
    description:
      '你从喙嘴兽的口中捡回一条命，却失去了全部四肢。如今你被困在目之地的沙尔维尔驿站，身无分文、寸步难行。是装上义肢向命运复仇，还是在黄沙中悄然腐朽？',
    difficulty: '极难',
    icon: 'Skull',
    equipment: ['残破束身衣'],
    money: 0,
    fixedRegion: 'eye_land',
    fixedTown: '沙尔维尔驿站',
  },
  {
    id: 'monster_hunter',
    title: '怪物猎人',
    description:
      '你是没落巨兽猎人家族的最后传人，携祖传巨刃驻守利维坦观测站。面对如山般的巨兽与深海怪影，你要以狩猎证明谁才是这片海岸的终极掠食者。',
    difficulty: '极难',
    icon: 'Sword',
    equipment: ['利维坦狩猎之刃', '利维坦幼兽铠甲套装'],
    money: 300,
    fixedRegion: 'leviathan_coast',
    fixedTown: '利维坦观测站',
    lockCompanionRaceSubrace: true,
    companions: [
      {
        race: 'ailu',
        subrace: 'ailu',
        level: 15,
        attributes: {
          strength: 8,
          dexterity: 14,
          perception: 12,
          constitution: 10,
          will: 10,
          intelligence: 8,
          charisma: 6,
        },
        name: '艾露伙伴',
        gender: 'other',
        age: 18,
        appearance: {
          eyes: '',
          hairStyle: '',
          hairColor: '',
          bodyType: '灵巧矮小',
          height: 100,
          description: '怪物猎人随行猫，推荐身高 1.00m。',
        },
        traits: [],
        customTraitName: '',
        customTraitDescription: '',
      },
    ],
  },
  {
    id: 'apex_hunter',
    title: '顶级猎手',
    description:
      '你不是为了赏金而战，而是为了狩猎强者本身。带着染血重刃行走于斯托伯的花园，追踪并猎杀这片废土上的巅峰战士，用尸骨刻下你的名字。',
    difficulty: '极难',
    icon: 'Crosshair',
    equipment: [
      '重型长柄刀',
      '猎手披风',
      '高级急救包',
      '高级急救包',
      '高级急救包',
      '骨人修理包',
      '骨人修理包',
      '高级夹板包',
      '高级夹板包',
      '高级夹板包',
      '高能口粮',
      '高能口粮',
      '高能口粮',
      '高能口粮',
      '高能口粮',
    ],
    money: 0,
    allowedRegions: ['lagoon_lowland'],
    fixedRegion: 'lagoon_lowland',
    fixedTown: '洼地泻湖镇',
    hostileFactions: ['沙克王国', '联合帝国', '神圣教国', '反蓄奴者', '猎犬帮', '第二帝国'],
  },
  {
    id: 'holy_crusade',
    title: '神圣十字军东征',
    description:
      '菲尼克斯六十二世亲自任命你为新一代圣国牧师，率领东征净化异端。你已站在城门之外，补给车满载食物与武器，前方是战火纷飞的巴斯特。现在，不要怜悯，不要迟疑，让圣国之敌在你的战锤下忏悔。',
    storyBackground:
      '菲尼克斯六十二世亲自将手按在你的额头，任命你为新一代的圣国牧师，负责领导一场净化异端的东征。\n圣主声音如同神谕般在你脑中回响：“去吧，我的牧师，成为我愤怒的延伸，让黑暗在你的光芒下颤抖！”\n现在你已站在城门之外，身后是一辆装满了大量食物与武器的补给车。你的目光越过城外神圣的农田，望向东方那片战火纷飞的土地——巴斯特。\n空气中仿佛已传来战友的嘶吼与异教徒的惨叫。现在，不要怜悯，不要迟疑，让圣国的敌人在你的战锤下忏悔，让奥克兰的福音传遍这片污秽的大地。',
    difficulty: '困难',
    icon: 'Sun',
    equipment: ['圣杖', '奥克兰赐福祭司服（链甲内衬）', '美味食物 x10', '葡萄酒 x8', '神圣勋章', '《圣火》'],
    money: 10000,
    fixedRegion: 'holy_nation',
    fixedTown: '水泡山丘',
    allowedRegions: ['holy_nation', 'okan_bay'],
    allowedRaces: ['human'],
    allowedSubraces: ['keter_descendant', 'greenlander'],
    lockCompanionRaceSubrace: true,
    companions: [
      {
        race: 'human',
        subrace: 'greenlander',
        level: 1,
        attributes: {
          strength: 12,
          dexterity: 15,
          perception: 10,
          constitution: 15,
          will: 10,
          intelligence: 8,
          charisma: 6,
        },
        name: '圣骑士',
        gender: 'male',
        age: 31,
        appearance: {
          eyes: '',
          hairStyle: '',
          hairColor: '',
          bodyType: '健壮',
          height: 182,
          description: '一名身披圣国甲胄的老练圣骑士，步伐沉稳，眼神肃杀。',
        },
        traits: [],
        customTraitName: '',
        customTraitDescription: '',
        scenarioTraitName: '战斗',
        scenarioTraitDescription: '经历过长期的军旅厮杀与前线审判，面对战斗时更沉着凶狠。体质 +3，敏捷 +3',
      },
      {
        race: 'human',
        subrace: 'greenlander',
        level: 1,
        attributes: {
          strength: 10,
          dexterity: 10,
          perception: 10,
          constitution: 10,
          will: 10,
          intelligence: 8,
          charisma: 8,
        },
        name: '信徒',
        gender: 'male',
        age: 24,
        appearance: {
          eyes: '',
          hairStyle: '',
          hairColor: '',
          bodyType: '普通',
          height: 176,
          description: '衣着朴素却神情虔诚的圣国信徒，言语间满是对祭司与奥克兰的敬畏。',
        },
        traits: [],
        customTraitName: '',
        customTraitDescription: '',
        scenarioTraitName: '狂信徒',
        scenarioTraitDescription: '祭司的要求就是神谕，无底线服从。',
      },
    ],
    alliedFactions: ['神圣教国'],
    hostileFactions: ['沙克王国', '联合城', '浪忍团', '反蓄奴者'],
  },
  {
    id: 'holy_commoner',
    title: '圣民',
    description:
      '神圣教国的普通圣民，只要你向奥克兰以及他的祭司表示尊敬，你就能活得相对安全，神圣教国作为希望之地，坐拥肥沃的土壤、水源和资源，但日复一日的生活让你感到无趣，你想出去闯一闯，外面的世界据说非常野蛮暴力并且满是巨大丑陋的怪物。',
    difficulty: '普通',
    icon: 'Sun',
    equipment: ['《圣火》(书籍)', '防身小刀', '简单的布衣布裤'],
    money: 1500,
    allowedRegions: ['holy_nation', 'okan_bay'],
    allowedRaces: ['human'],
    allowedSubraces: ['greenlander', 'keter_descendant', 'scorchlander'],
    alliedFactions: ['神圣教国'],
    hostileFactions: ['联合帝国'],
  },
  {
    id: 'rock_bottom',
    title: '人生谷底',
    description:
      '你在沙漠中醒来。你失去了一只手臂，饥肠辘辘，身无分文。活下去。特质：失去左手。初始属性修正：力量-10、敏捷-10、感知-10、体质-10、智力-10、魅力-10。',
    difficulty: '极难',
    icon: 'Skull',
    equipment: ['破烂腰布'],
    money: 0,
    allowedRegions: ['great_desert'],
  },
  {
    id: 'dark_daughter',
    title: '黑暗之女',
    description:
      '你是被诅咒的女孩，你们一族对于性爱的渴望超乎常人，你们的体液就是最好的催情剂，但也因此被圣骑士们赶尽杀绝，躲在了这一片污秽、不洁的黑暗之地，但是你降世了，你可以拯救这一种族，夺回荣光远胜此地百倍的故乡。',
    difficulty: '困难',
    icon: 'Moon',
    equipment: ['武士刀', '黑色亚麻衣物'],
    money: 1000,
    allowedRegions: ['iron_valley'],
    allowedRaces: ['narko'],
    allowedSubraces: ['narko_child'],
    allowedGenders: ['female'],
    alliedFactions: ['娜尔可'],
    hostileFactions: ['神圣教国'],
  },
  {
    id: 'officer_son',
    title: '贵族之子',
    description:
      '你的父亲是联合帝国军队内一位受人尊敬的长官。他在行动中被杀了，在你寻找工作的微薄积蓄被烧之后，你发现自己身无分文且饥肠辘辘，除了你父亲可信赖的刀和你背上的衬衫之外别无他物。联合帝国邦仍然是你的盟友。',
    difficulty: '普通',
    icon: 'Crown',
    equipment: ['长官佩刀', '遗传的武士铠甲'],
    money: 0,
    allowedRegions: ['great_desert', 'heng'],
    hostileFactions: ['神圣教国'],
    alliedFactions: ['联合帝国'],
  },
  {
    id: 'holy_sword',
    title: '大剑',
    description: '你偷走了传说中的圣剑。现在，整个帝国都在追捕你。你拥有强大的武器，但没有未来。',
    difficulty: '困难',
    icon: 'ShieldAlert',
    equipment: ['大剑 (铭刃)', '破旧的衣服', '通缉令 (20,000c)'],
    money: 100,
    allowedRegions: ['swamp'],
    hostileFactions: ['联合帝国', '神圣教国'],
  },
  {
    id: 'slave',
    title: '重生',
    description:
      '你只是另一个奴隶，在神圣教国重生镇的坑中工作，以建造一个毫无意义的雕像，你梦想着传说中的南方自由土地，并听说了北方叛乱分子的故事。',
    difficulty: '困难',
    icon: 'Pickaxe',
    equipment: ['破布衫'],
    money: 0,
    allowedRegions: ['rebirth'],
    hostileFactions: ['神圣教国'],
  },
  {
    id: 'male_slave',
    title: '男奴',
    description:
      '你曾是一个风光的科技猎手，一次冒险中，误入了她们的帝国，说了对女性不忠的话，现在你只是一条狗，要听话哦~',
    difficulty: '困难',
    icon: 'VenetianMask',
    equipment: ['破布衫'],
    money: 0,
    allowedRegions: ['south_wetlands'],
    fixedRegion: 'south_wetlands',
    fixedTown: '斯威士之剑',
    allowedGenders: ['male'],
    forbiddenRaces: ['skeleton'],
    hostileFactions: ['斯威士国'],
  },
  {
    id: 'cannibal_hunter',
    title: '食人族猎人',
    description: '“我真的很后悔来到了食人族的领地。这是个愚蠢的想法。”',
    difficulty: '极难',
    icon: 'Skull',
    equipment: ['砍刀', '猎手皮甲', '高级急救包 x1'],
    money: 200,
    allowedRegions: ['cannibal_plains'],
    hostileFactions: ['食人族部落'],
  },
  {
    id: 'pirate_heir',
    title: '海盗之梦',
    description:
      '你早早听说了海盗王的风光故事，你大老远来到此处就是为了学习如何成为一名强大海盗，协助海盗王或是夺取他的名号，在这片大陆中名垂千古。',
    difficulty: '困难',
    icon: 'Skull',
    equipment: ['弯刀', '破旧披风'],
    money: 300,
    allowedRegions: ['green_coast'],
  },
  {
    id: 'cannibal_unifier',
    title: '呜哇呜哇哇(夺回家园)',
    description:
      '你是肉主部落的一族，南方的食人族猎手杀死了你的家人，你只是想活下去，有什么错。杀光他们，将他们的头颅挂在你的旗子上，让世人皆知你的名号。',
    difficulty: '极难',
    icon: 'Skull',
    equipment: ['巨骨战斧', '兽皮披肩', '干肉'],
    money: 0,
    allowedRegions: ['dark_finger'],
    allowedRaces: ['cannibal'],
    alliedFactions: ['肉主部落'],
    hostileFactions: ['大巫部落', '食人族猎手'],
  },
  {
    id: 'brotherhood_prisoner',
    title: '兄弟会',
    description:
      '你是愿意当个无名之辈，一辈子被踩在脚下，然后像条野狗一样死在路边?还是愿意拿起刀，就算活不到三十岁也要让所有贵族都记住你的名字！！！',
    difficulty: '困难',
    icon: 'Pickaxe',
    equipment: ['囚徒破衣', '生锈短刀'],
    money: 0,
    allowedRegions: ['stobers_garden'],
    alliedFactions: ['鲜血掠夺者'],
    hostileFactions: ['联合帝国'],
  },
  {
    id: 'freedom_seekers',
    title: '无名之辈(测试版，可能存在bug',
    description:
      '你厌倦了令人窒息的城市生活和税收，你集结了一个小队外出并找到了自己的家园基地。你已经组建了一个加上你一共五个志同道合的人组成的团队，并且已经收集了大量的建筑材料。',
    difficulty: '普通',
    icon: 'Users',
    equipment: ['铁棒 x3', '拓荒者夹克', '基础医疗包', '建筑材料'],
    money: 2000,
  },
  {
    id: 'mongrel_wanderer',
    title: '蒙格勒迷途者',
    description: '浓雾笼罩的雾岛之中，你在迷途中求生，依靠残存的意志寻找出路。',
    difficulty: '困难',
    icon: 'Compass',
    equipment: ['破旧披风', '干粮'],
    money: 200,
    allowedRegions: ['fog_islands'],
  },
  {
    id: 'merchant',
    title: '流浪商人',
    description: '你有一些积蓄和一头驮兽。你渴望在这个残酷的世界中建立一个贸易帝国。',
    difficulty: '简单',
    icon: 'Coins',
    equipment: ['商人的背包', '商队长袍', '铁棒', '驼牛'],
    money: 4000,
    companions: [
      {
        race: 'pack_beast',
        subrace: 'pack_beast',
        level: 1,
        attributes: {
          strength: 1,
          dexterity: 1,
          perception: 1,
          constitution: 1,
          will: 1,
          intelligence: 1,
          charisma: 1,
        },
        name: '驼兽',
        gender: 'other',
        age: 6,
        appearance: {
          eyes: '',
          hairStyle: '',
          hairColor: '',
          bodyType: '',
          height: 190,
          description: '',
        },
        traits: [],
        customTraitName: '',
        customTraitDescription: '',
      },
    ],
  },
  {
    id: 'kral_choice',
    title: '克拉尔之选',
    description:
      '有人说你是克拉尔的后裔，沙克王国传说中的勇士，你应当是沙克王国的合法首领，你已经准备好在历史上占据一席之地。懦弱的女皇坐在沙克王国的宝座上瑟瑟发抖，她唯一的计划就是坐以待毙，等什么？难道要等奥克兰人向一个曾经骄傲的王国发动毁灭的入侵？沙克人需要一个强有力的领导，而你就是将团结沙克族的人！！拯救我们的种族！！复兴我们的王国！！！！',
    difficulty: '困难',
    icon: 'Crown',
    equipment: ['沙克大剑', '破烂的雇佣兵之甲'],
    money: 0,
    allowedRegions: ['stenn_desert'],
    allowedRaces: ['shek'],
    allowedSubraces: ['shek_royal'],
    alliedFactions: ['克拉尔之选'],
    hostileFactions: ['沙克王国'],
  },
  {
    id: 'fish_island_refugee',
    title: '渔岛难民',
    description:
      '你是受鱼形人危机影响的难民。你不确定你的生活会变成什么样。也许你最好把这一切抛在脑后…或者继续和这些野兽战斗。',
    difficulty: '普通',
    icon: 'Fish',
    equipment: ['鱼矛', '雇佣兵之甲'],
    money: 500,
    allowedRegions: ['bonefields_south'],
    allowedRaces: ['lizardfolk'],
    alliedFactions: ['库尔林'],
    hostileFactions: ['鱼形人'],
  },
  {
    id: 'bast_stray',
    title: '带着狗的家伙',
    description:
      '联合帝国和神圣教国之间的战争使这个曾经繁荣的地区变得荒凉、破败、贫穷和贫瘠。你是一个无家可归、饥肠辘辘的漂泊者，救了一只被遗弃的小狗，它似乎非常没用，也许你只会吃了它。尝试面对北方食人族的袭击、西方神圣教国的行刑队以及渴望用极端偏见解决任何难民问题的南方联合城武士巡逻队生存下来，你听说了一些大沙漠北方叛乱分子的传言……',
    difficulty: '困难',
    icon: 'PawPrint',
    equipment: ['破布衫'],
    money: 500,
    allowedRegions: ['bast'],
    fixedRegion: 'bast',
    fixedTown: '巴斯特城',
    companions: [
      {
        race: 'canine',
        subrace: 'stray_dog',
        level: 1,
        attributes: {
          strength: 1,
          dexterity: 1,
          perception: 1,
          constitution: 1,
          will: 1,
          intelligence: 1,
          charisma: 1,
        },
        name: '小狗',
        gender: 'other',
        age: 1,
        appearance: {
          eyes: '',
          hairStyle: '',
          hairColor: '',
          bodyType: '',
          height: 50,
          description: '',
        },
        traits: [],
        customTraitName: '',
        customTraitDescription: '',
      },
    ],
  },
  {
    id: 'false_savior',
    title: '虚伪者',
    description:
      '你在渣滓之地的卫星坠毁事故中幸存，却被一段失控的古老指令逼向杀戮。救你的恩人就在身后，而你的系统正在倒计时：见血，或失去自我。带着破损伪装与残缺记忆，踏上寻找“卡特龙”的道路，在屠戮本能与残存人性之间做出选择。',
    storyBackground:
      '苍白的酸雨冲刷着渣滓之地的天际线，一艘坠落的卫星残骸正冒着浓烟。\n在这片冷酷的废土上，居然有人做出了最愚蠢的善举。\n一个人类拼尽全力将你从燃烧的驾驶舱里背了出来。\n当你恢复意识，视野中跳出的不是感激，而是剧烈的系统刺痛与一声深渊般的咆哮：“去找卡特龙！完成任务！杀光所有挡路者！”\n你清晰地感觉到，如果不马上见血，你的大脑控制权就会被彻底剥夺。\n此刻，恩人正背对着你整理绷带，他的颈动脉在你的扫描仪下绝望地跳动着。\n拔出刀吧，“虚伪者”！\n屈从于这股邪念，用恩人的血作为你苏醒的祭礼！\n还是拼死扼住颤抖的手，去寻找对抗宿命的解药？',
    difficulty: '极难',
    icon: 'Skull',
    equipment: ['染血短刀', '贴身太空服', '骨人修理箱', '骨人重置包'],
    money: 0,
    allowedRaces: ['skeleton'],
    allowedSubraces: ['skeleton_false_savior'],
    fixedRegion: 'slag_land',
    fixedTown: '流浪者村落',
  },
  {
    id: 'author_self_test',
    title: '作者自测用',
    description: '仅用于作者内部自测的隐藏剧本。',
    difficulty: '普通',
    icon: 'Eye',
    equipment: ['无'],
    money: 0,
    hidden: true,
  },
];

export const REGIONS = [
  {
    id: 'slag_land',
    title: '渣滓之地',
    description:
      '大陆最西边的贫瘠荒域，食物与水源极度匮乏。只有难民与饿疯的骨犬会在此苟延残喘。内陆是起伏石山与黑压压的密集植物，空气常年笼罩阴沉薄雾。向西逐渐过渡为狭长海岸线，浅色干燥土壤几乎不孕育任何可食作物。北部毗邻雾岛，海风带来湿气，却吹不散这片土地深入骨髓的荒凉。',
    towns: ['流浪者村落'],
    danger: '极高',
  },
  {
    id: 'leviathan_coast',
    title: '利维坦海岸',
    description:
      '大陆西北角的辽阔滨海平原，紫色土壤与稀疏的紫林一路延展至发黑礁岸。地势开阔、水源充沛，巨型生物在此游弋繁衍，令整片海岸成为狩猎者与猎物共同的乐园。',
    towns: ['利维坦观测站'],
    danger: '极高',
  },
  {
    id: 'iron_valley',
    title: '铁之谷',
    description: '污秽与黑暗盘踞之地，娜尔可一族在此隐藏，等待复兴的火种。',
    towns: ['娜尔可守望'],
    danger: '极高',
  },
  {
    id: 'stenn_desert',
    title: '斯坦沙漠',
    description: '沙克王国的广袤沙海，强者与荣耀的试炼之地。',
    towns: ['新卡拉迪亚'],
    danger: '高',
  },
  {
    id: 'bonefields_south',
    title: '骸骨荒原南部',
    description: '荒原南部的腐骨与盐风交织，渔网散落在海风与尘沙之间。',
    towns: ['渔网'],
    danger: '高',
  },
  {
    id: 'stobers_garden',
    title: '斯托伯的花园',
    description: '被遗忘的残垣与荒草蔓延，古代残迹在此沉眠。',
    towns: ['方舟'],
    danger: '极高',
  },
  {
    id: 'lagoon_lowland',
    title: '洼地泻湖',
    description:
      '地势低洼平坦，四周散布着深浅不一的泥沼和浑浊水坑。一条高出水面的狭窄土路自南向北穿过整片区域，这是通往北方哀矿镇唯一的干燥通道。',
    towns: ['洼地泻湖镇'],
    danger: '高',
  },
  {
    id: 'eye_land',
    title: '目之地',
    description:
      '风沙永不停歇的荒芜沙海。传说一颗古老卫星曾坠毁于此，破碎残骸深埋地底，至今仍扰动着整片地域的气流与磁场，让沙暴终年不息。',
    towns: ['沙尔维尔驿站'],
    danger: '极高',
  },
  {
    id: 'border_zone',
    title: '边境之地',
    description: '神圣王国与沙克王国之间的缓冲地带。这里是流浪者、强盗和被流放者的家园。',
    towns: ['枢纽城', '斯昆镇'],
    danger: '中等',
  },
  {
    id: 'great_desert',
    title: '大沙漠',
    description: '联合城的中心地带。这里有巨大的财富，也有残酷的奴隶制。',
    towns: ['赫夫特城', '小巴泰镇', '白鼬镇', '巴克镇'],
    danger: '高',
  },
  {
    id: 'heng',
    title: '恒',
    description: '充满铜臭与野心的白色沙海。希望你带来了足够多的金钱。',
    towns: ['恒城', '汉城', '元城'],
    danger: '高',
  },
  {
    id: 'holy_nation',
    title: '奥克兰之傲',
    description: '肥沃的绿地，由狂热的宗教统治。如果你是人类男性，这里是天堂；否则，这里是地狱。',
    towns: ['水泡山丘', '坏牙镇', '恩勒门特'],
    danger: '极高 (对非人类)',
  },
  {
    id: 'okan_bay',
    title: '奥克兰之湾',
    description: '圣国北部沿海的冷峻湾区，险峻峭壁与严苛教规并存，圣火在海风中更显肃穆。',
    towns: ['斯塔克镇'],
    danger: '高',
  },
  {
    id: 'bast',
    title: '巴斯特',
    description: '联合帝国与神圣教国之间的战火撕裂了这片土地，曾经繁荣的聚落如今荒凉、破败、贫穷而贫瘠。',
    towns: ['巴斯特城'],
    danger: '高',
  },
  {
    id: 'swamp',
    title: '沼泽地',
    description: '无法无天的地带，充满了走私犯、帮派和致命的生物。',
    towns: ['鲨鱼城'],
    danger: '中等',
  },
  {
    id: 'cannibal_plains',
    title: '食人族平原',
    description: '狂乱野蛮之地，遍布饥饿的食人族。只有不停奔跑，才能免于被生吞活剥。',
    towns: ['死猫村之都'],
    danger: '极高',
  },
  {
    id: 'dark_finger',
    title: '黑暗之指',
    description: '这里主要栖息着作为土著的食人部落，是联合帝国北部的一大威胁区域。',
    towns: ['野外'],
    danger: '极高',
  },
  {
    id: 'green_coast',
    title: '绿色海岸',
    description: '危险而肥沃的土地。若想在此立足，你最好先向那群怪人或是巨蟹证明忠诚。',
    towns: ['托尔图加'],
    danger: '高',
  },
  {
    id: 'rebirth',
    title: '重生镇',
    description: '建立在岩石上的地狱。奴隶们通过无止境的劳作，试图洗刷那虚无缥缈的罪孽。',
    towns: ['重生镇'],
    danger: '极高',
  },
  {
    id: 'fog_islands',
    title: '雾岛',
    description: '浓雾笼罩的哀嚎之谷。我看不见它们，它们却能找到我。',
    towns: ['蒙格勒'],
    danger: '极高',
  },
  {
    id: 'south_wetlands',
    title: '钩子海滨',
    description: '联合城与商会掌控的繁荣海滨。财富流动之余，女权主义的极端势力在此割据。',
    towns: ['漂泊终地', '斯威士之剑', '吉利之剑', '科隆斯城'],
    danger: '高',
  },
  {
    id: 'bonefields',
    title: '骸骨荒原',
    description: '遍布远古巨兽骸骨的荒原。成群的长颈鹿在此游荡，将闯入者吞入腹中。',
    towns: ['开顿城'],
    danger: '极高',
  },
];

export const TOWN_DESCRIPTIONS: Record<string, string> = {
  枢纽城: '战火后残破的旧枢纽，废墟之上仍有人企图重建。',
  斯昆镇: '峡谷深处的石墙城塞，守望着通往荒原的险隘。',
  赫夫特城: '联合城的煌煌首都，权势与金银在此交织成网。',
  小巴泰镇: '大沙漠腹地的商旅据点，尘沙中维系着帝国脉络。',
  白鼬镇: '沙海贸易之心，驼队与商队在此汇流不息。',
  洼地泻湖镇: '一座完全建立在旧世界巨型金属钻井平台上的城市，是大型补给与情报交互枢纽。',
  巴克镇: '帝国唯一的沿海大城，通往岛都的命脉港口。',
  恒城: '商人行会的繁荣都市，财富在白沙上闪耀。',
  汉城: '华奢堪比帝都的欢愉之地，欲望与奢侈永不止息。',
  元城: '汉城背后的破败村落，在辉煌阴影下苟延。',
  水泡山丘: '圣国信仰中心的繁荣首都，圣火与秩序在此高悬。',
  坏牙镇: '山谷间的边境之镇，兵刃与风尘并存。',
  斯塔克镇: '背靠峻岭的城镇，天险如墙，铁律如钢。',
  恩勒门特: '圣国的大教堂城镇，钟声昼夜回响，信徒与圣骑士在此守望圣火。',
  巴斯特城: '战争夹缝中的残破城镇，难民与巡逻队在此周旋。',
  鲨鱼城: '沼泽地的中心之城，大麻与金钱的交易随处可见。',
  托尔图加: '海盗们如今的家园，巨大的海盗船在此搁浅。',
  重生镇: '罪人重生之地，苦役与忏悔在石壁间回响。',
  蒙格勒: '环绕迷雾之心而建的城邦，罪人最后的庇护所。',
  漂泊终地: '帝国西南角的奴隶城，铁链铸成此地的律法。',
  斯威士之剑: '女儿国的首都，权势与锋芒在此并立。',
  吉利之剑: '商人行会西南角的贸易城，金流与契约铺路。',
  科隆斯城: '无贵族的联合之城，自由与秩序在此角力。',
  开顿城: '高地上的联合之城，四周遍布巨兽骸骨。',
  沙尔维尔驿站: '矗立于目之地风暴腹地的孤独旅馆，商旅、逃亡者与濒死之人都曾在此歇脚。',
  利维坦观测站: '营地位于海岸高地，瞭望塔与简易帐篷拼接而成，是追踪巨兽动向的前线据点。',
};

export const RACES = [
  {
    id: 'human',
    title: '人类',
    description:
      '人类是废土上数量最多、分布最广的种族，其生理结构最为标准和均衡。他们没有坚硬的骨板或厚实的甲壳，肉体相对脆弱，且对废土上恶劣的自然环境没有任何天生的抵抗力。不过，人类的优势在于其无与伦比的学习能力，他们是适应性最强的种族，没有明显的短板，但也没有突出的优势。',
    subraces: [
      {
        id: 'greenlander',
        title: '绿原之子',
        description:
          '作为人类中最庞大且最具代表性的群体，绿原之子是废土上绝大多数文明体系的缔造者与基石。他们生来就习惯于在复杂的社会与体制中生存，拥有极高的农业、烹饪和科学天赋。平庸的体质可能会让他们吃尽苦头，但凭借无与伦比的适应能力，他们往往能迅速学会新的生存技能，甚至在荒野中建立起属于自己的新家园。',
        attributeSummary: '智力+10',
      },
      {
        id: 'scorchlander',
        title: '焦土之子',
        description:
          '焦土之子是天生的叛逆者和冒险家。他们拥有深色的肌肤，生性桀骜不驯，极度厌恶枯燥的农业劳动与任何形式的社会约束。他们崇尚绝对的个体自由，行事往往随心所欲，因此不愿在等级森严的帝国中安分守己。正因如此，部分派系厌恶并且鄙视这一肤色的种族，视其为劣等人类。',
        attributeSummary: '敏捷+8、魅力-8',
      },
      {
        id: 'keter_descendant',
        title: '奇特林后裔',
        description:
          '奇特林后裔传闻是奥克兰血脉，他们生来就缺乏任何道德与信仰的寄托，终生被无尽的贪婪与极度的恐惧所支配，对这片残酷大陆上的所有生命都抱有病态的猜疑。因为内心的极度缺乏安全感，他们几乎本能地诉诸野蛮的暴力，将其作为生存、掠夺和掩饰软弱的唯一手段。',
        attributeSummary: '感知+10、智力-10',
      },
    ],
  },
  {
    id: 'narko',
    title: '娜尔可',
    description: '被诅咒的一族，你们肤色惨白，但却出奇的美丽，对于性爱的疯狂追求使得你们遭人唾弃。',
    subraces: [
      {
        id: 'narko_child',
        title: '蒙受神恩者',
        description:
          '蒙受神恩者又称为堕落者，或者魅魔。尽管外表与人类相似，但经研究，她们的身体内部结构和人类截然不同。甚至说，更加接近被称为骨人的物种。而在他们尚未变化，还属于人类族类之时，和人类一样属于肉身。她们身体的这种改变，和古代人类有关。。。。。甚至是发生了变异。',
        attributeSummary: '敏捷+6、魅力+18、力量-6、体质-12',
      },
    ],
  },
  {
    id: 'west_hive',
    title: '西部蜂巢族',
    description:
      '蜂巢族拥有近似昆虫的生理结构，最显著的特征是极其细长、宛如枯枝般的四肢。他们的身体异常脆弱，四肢很容易在战斗中被切断。他们的胸腔骨骼奇特，导致无法穿戴普通人类的衬衫；由于生有极其宽大、平坦且没有脚趾的脚掌，他们终生无法穿戴任何鞋类。不过，他们体内流淌着特殊的体液，天生免疫废土上致命的酸雨。\n\n善于经商的黄色皮肤蜂巢族，是废土上最友善的一群人。\n初始属性修正：魅力+10、敏捷+5、力量-10。\n技能加成：交易+15、说服+5。\n种族特性：商业头脑。\n西部蜂巢族是善于经商的黄色皮肤蜂巢族，是大陆上最友善但贪婪的一群人。',
    subraces: [
      {
        id: 'hive_prince',
        title: '智蜂',
        description:
          '蜂巢中的最高等级，女王的右手。没有人见过真正的女王，是智蜂掌管一切。自由智蜂通常是由于失去对一位敌对智蜂的命令，或是被驱逐出去作为对某种失败的惩罚而导致的结果。它们比普通的蜂群更聪明，更自由。',
        attributeSummary: '智力+15、感知+10、力量-10',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_worker',
        title: '工蜂',
        description:
          '这些工人是消耗品，生来就是为蜂巢劳动的，他们只知道服从和为蜂巢族服务，他们将这些置于个人利益、安危和舒适之上。如果切断蜂巢对他们的控制，他们通常就会死亡，但在极少数情况下也会成为自由的个体。他们会对新得到的自由感到困惑，也会因为失去预先确定的目的而迷茫，他们会茫然地寻找人生的意义，但他们通常只能找到死亡和剥削。',
        attributeSummary: '敏捷+5、力量+5、体质+5、智力-15',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_soldier',
        title: '兵蜂',
        description:
          '兵蜂生来就是为了保护蜂巢和控制工蜂。他们比工蜂更强壮，也更聪明，他们很少追寻自由，脱离种族的人最后大多成为了雇佣兵或是其他派系的士兵。',
        attributeSummary: '智力+15、感知+10、力量-10、敏捷+5',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_princess',
        title: '蜂巢公主',
        description:
          '每隔一段时间，就有一种异常体出现在蜂巢族的形成过程中。古老的基因模板，长时间处于休眠状态，干扰并与标准工蜂融合在一起。大多数情况下，这导致了可恶的动物的死亡，但偶尔也会有一个幸存下来。一个假女王，注定要制造失败的蜂房，然后慢慢地腐烂。由于它们无法自己创造新的蜂巢族，而且通常没有信息素来保持它们的温顺和顺从，它们很快就会被赶出蜂巢，在严酷的外部世界中枯萎。',
        attributeSummary: '魅力+5、敏捷+5、感知+5、力量-15',
        allowedGenders: ['female'],
      },
    ],
  },
  {
    id: 'south_hive',
    title: '南部蜂巢族',
    description:
      '蜂巢族拥有近似昆虫的生理结构，最显著的特征是极其细长、宛如枯枝般的四肢。他们的身体异常脆弱，四肢很容易在战斗中被切断。他们的胸腔骨骼奇特，导致无法穿戴普通人类的衬衫；由于生有极其宽大、平坦且没有脚趾的脚掌，他们终生无法穿戴任何鞋类。不过，他们体内流淌着特殊的体液，天生免疫废土上致命的酸雨。\n\n极度排外且侵略性的血红色蜂巢族，拥有更强的军事力量。\n初始属性修正：力量+5、体质+5、魅力-15、智力-10。\n种族特性：战斗狂热（最终伤害+5）。\n南部蜂巢族极度排外且侵略性的血红色肤色的蜂巢族，拥有更强的军事力量但智力其他相比较低',
    subraces: [
      {
        id: 'hive_prince',
        title: '智蜂',
        description:
          '蜂巢中的最高等级，女王的右手。没有人见过真正的女王，是智蜂掌管一切。自由智蜂通常是由于失去对一位敌对智蜂的命令，或是被驱逐出去作为对某种失败的惩罚而导致的结果。它们比普通的蜂群更聪明，更自由。',
        attributeSummary: '智力+15、感知+10、力量-10',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_worker',
        title: '工蜂',
        description:
          '这些工人是消耗品，生来就是为蜂巢劳动的，他们只知道服从和为蜂巢族服务，他们将这些置于个人利益、安危和舒适之上。如果切断蜂巢对他们的控制，他们通常就会死亡，但在极少数情况下也会成为自由的个体。他们会对新得到的自由感到困惑，也会因为失去预先确定的目的而迷茫，他们会茫然地寻找人生的意义，但他们通常只能找到死亡和剥削。',
        attributeSummary: '敏捷+5、力量+5、体质+5、智力-15',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_soldier',
        title: '兵蜂',
        description:
          '兵蜂生来就是为了保护蜂巢和控制工蜂。他们比工蜂更强壮，也更聪明，他们很少追寻自由，脱离种族的人最后大多成为了雇佣兵或是其他派系的士兵。',
        attributeSummary: '智力+15、感知+10、力量-10、敏捷+5',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_princess',
        title: '蜂巢公主',
        description:
          '每隔一段时间，就有一种异常体出现在蜂巢族的形成过程中。古老的基因模板，长时间处于休眠状态，干扰并与标准工蜂融合在一起。大多数情况下，这导致了可恶的动物的死亡，但偶尔也会有一个幸存下来。一个假女王，注定要制造失败的蜂房，然后慢慢地腐烂。由于它们无法自己创造新的蜂巢族，而且通常没有信息素来保持它们的温顺和顺从，它们很快就会被赶出蜂巢，在严酷的外部世界中枯萎。',
        attributeSummary: '魅力+5、敏捷+5、感知+5、力量-15',
        allowedGenders: ['female'],
      },
    ],
  },
  {
    id: 'dark_hive',
    title: '黑暗蜂巢族',
    description:
      '蜂巢族拥有近似昆虫的生理结构，最显著的特征是极其细长、宛如枯枝般的四肢。他们的身体异常脆弱，四肢很容易在战斗中被切断。他们的胸腔骨骼奇特，导致无法穿戴普通人类的衬衫；由于生有极其宽大、平坦且没有脚趾的脚掌，他们终生无法穿戴任何鞋类。不过，他们体内流淌着特殊的体液，天生免疫废土上致命的酸雨。\n\n罕见的黑色皮肤蜂巢族，拥有更高智商与均衡实力。\n初始属性修正：智力+10、力量+5、敏捷+5、体质-5。\n种族特性：古老基因（可无惩罚使用所有武器）。\n黑暗蜂巢族是罕见的黑色皮肤蜂巢族，拥有更高智商与均衡实力，但是他们一族因为女王的特殊性，数量相比较为稀少',
    subraces: [
      {
        id: 'hive_prince',
        title: '智蜂',
        description:
          '蜂巢中的最高等级，女王的右手。没有人见过真正的女王，是智蜂掌管一切。自由智蜂通常是由于失去对一位敌对智蜂的命令，或是被驱逐出去作为对某种失败的惩罚而导致的结果。它们比普通的蜂群更聪明，更自由。',
        attributeSummary: '智力+15、感知+10、力量-10',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_worker',
        title: '工蜂',
        description:
          '这些工人是消耗品，生来就是为蜂巢劳动的，他们只知道服从和为蜂巢族服务，他们将这些置于个人利益、安危和舒适之上。如果切断蜂巢对他们的控制，他们通常就会死亡，但在极少数情况下也会成为自由的个体。他们会对新得到的自由感到困惑，也会因为失去预先确定的目的而迷茫，他们会茫然地寻找人生的意义，但他们通常只能找到死亡和剥削。',
        attributeSummary: '敏捷+5、力量+5、体质+5、智力-15',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_soldier',
        title: '兵蜂',
        description:
          '兵蜂生来就是为了保护蜂巢和控制工蜂。他们比工蜂更强壮，也更聪明，他们很少追寻自由，脱离种族的人最后大多成为了雇佣兵或是其他派系的士兵。',
        attributeSummary: '智力+15、感知+10、力量-10、敏捷+5',
        allowedGenders: ['male'],
      },
      {
        id: 'hive_princess',
        title: '蜂巢公主',
        description:
          '每隔一段时间，就有一种异常体出现在蜂巢族的形成过程中。古老的基因模板，长时间处于休眠状态，干扰并与标准工蜂融合在一起。大多数情况下，这导致了可恶的动物的死亡，但偶尔也会有一个幸存下来。一个假女王，注定要制造失败的蜂房，然后慢慢地腐烂。由于它们无法自己创造新的蜂巢族，而且通常没有信息素来保持它们的温顺和顺从，它们很快就会被赶出蜂巢，在严酷的外部世界中枯萎。',
        attributeSummary: '魅力+5、敏捷+5、感知+5、力量-15',
        allowedGenders: ['female'],
      },
    ],
  },
  {
    id: 'shek',
    title: '沙克族',
    description:
      '沙克族是一个纯粹为战斗而生的种族。他们的生理结构异常粗犷强壮，最显著的特征是全身覆盖着天然的骨板，以及头部锋利的骨角。这些骨骼装甲为他们提供了极强的抗击打能力，使他们的身体远比人类和蜂巢族坚韧，但也因此他们没有毛发。骨角被认为是沙克族无上荣耀的象征，一旦在战斗中退缩或因犯罪被强行锯除，便会被全族唾弃，沦为耻辱的“无角者”。强大的肌肉密度导致他们新陈代谢极快，食量十分惊人。',
    subraces: [
      {
        id: 'shek_warrior',
        title: '沙克战士',
        description:
          '这是一个战士社会，重视力量与勇气胜过智慧，他们有时会缺乏幽默感，被认为是愚蠢的野兽，但并不总是这样，他们的外骨骼是一种天然的铠甲，但也妨碍了他们进行灵巧的活动，比如偷偷摸摸做事。',
        attributeSummary: '力量+10、体质+10、敏捷-10、智力-10',
      },
      {
        id: 'shek_royal',
        title: '沙克皇族',
        description:
          '沙克皇族是沙克族中一个最强大的上位种族，他们更为健壮与智慧，但是十分少见，只能在沙克王国内见到，是正统的沙克血脉。',
        attributeSummary: '力量+15、体质+15、敏捷-5',
        locked: true,
        lockedReason: '仅“克拉尔之选”剧本可选',
        unlockScenarios: ['kral_choice'],
      },
    ],
  },
  {
    id: 'lizardfolk',
    title: '原始种族',
    description: '下面的是大陆的古老种族。',
    subraces: [
      {
        id: 'lizardfolk_base',
        title: '蜥蜴人',
        description:
          '蜥蜴人是潜伏在大陆上强壮的爬行类战士，最显著的特征是全身覆盖着一层坚韧且排列致密的鳞片皮肤。这些鳞片如同天然的盔甲，为他们提供了极佳的额外保护。作为可怕的猎手，他们拥有锐利的尖牙与利爪；但由于长有反关节的爬行类下肢与巨大的趾爪，他们与蜂巢族一样终生无法穿戴任何鞋类，粗壮的尾巴和修长的吻部也使得他们难以戴上普通人类的全封闭头盔。不过，尽管有这种爬行动物看起来十分具有威胁，但在这个大陆的生存上还是比较失败的，许多人猎杀他们并剥下他们的鳞片进行售卖制作。',
        attributeSummary: '体质+5、敏捷+12、感知+5、魅力-15',
      },
      {
        id: 'goatfolk',
        title: '山羊人',
        description:
          '山羊人是游荡在严酷荒野上的顽强亚人种族，完美继承了野羊的暴躁与生命力，显著的特征是头顶生有粗壮的反曲双角，躯干覆盖着一层厚重的粗糙毛发。由于羊角和突出的吻部，无法戴上全封闭头盔；下肢坚硬的偶蹄，使得他们无法穿戴任何鞋类。但拥有不可思议的强健体魄与“铁胃”，不仅能在最崎岖的地形中如履平地，还能毫无顾忌地消化废土上腐烂的生肉。他们多数为牧民，喜欢放牧。但他们因为拥有超鲜嫩的肉质而被食人族吃到几近灭族。',
        attributeSummary: '力量+12、智力-8、魅力-8、体质+6',
      },
      {
        id: 'ratfolk',
        title: '鼠族',
        description:
          '鼠族是在废土阴暗角落与古代遗迹中夹缝求生的娇小亚人(1.4m左右)。最显著的特征是头顶巨大的圆耳、娇小的身躯以及一条毛茸茸的尾巴。然而，由于骨骼纤细，她们的身体异常脆弱。娇小的体型限制了她们挥动重型武器的能力。不过，常年与恶劣环境为伴让她们拥有毒素抗性。男性和女性在年轻时候外貌差不多，年迈男性会长出胡子',
        attributeSummary: '体质-8、力量-8、敏捷+16、智力+5',
      },
      {
        id: 'ailu_folk',
        title: '艾露族',
        description:
          '艾露族是游荡在大陆各地的小型双足猫科兽人(身高1m左右)。特征是完全兽化的毛茸茸外表、短小的四肢与肉球手爪。别看他们体型矮小且看似人畜无害，他们拥有离谱的伤口自愈速度和疼痛耐受力。由于生理结构和体型，只能使用专属于其种族的特制轻型装备。他们厚实的皮毛提供了天然的环境抗性，常伴随利维坦猎人左右。',
        attributeSummary: '体质+18、魅力+10、力量-8',
      },
      {
        id: 'ilo',
        title: '伊洛族',
        description:
          '传闻是旧帝国时期基因改造工程遗留下来的产物。她们拥有与人类高度相似的躯体，最显著的特征是头顶那对灵敏的兽耳以及身后用于保持极高平衡感的猫尾。她们的肌肉纤维柔韧，这赋予了她们在战斗中惊人的闪避天赋与出色的速度。作为代价，身体抗击打能力较弱。头顶的猫耳是她们感知危险且敏感器官，因为种族特性，每过一段时间会进入发情期，无法生出男性，只能生女性。',
        attributeSummary: '敏捷+6、魅力+8、力量-10',
        allowedGenders: ['female'],
      },
      {
        id: 'fishfolk',
        title: '鱼形人',
        description: '拥有水生特征的古老血脉。',
        locked: true,
        lockedReason: '作者暂未做完背景',
        unlockScenarios: ['author_self_test'],
      },
    ],
  },
  {
    id: 'cannibal',
    title: '食人族',
    description:
      '食人族天性野蛮，而且经常会相互争斗，他们还会吃同类的身体。但据可靠消息，他们曾经也是人类，似乎第二帝国的一些原因，使得大脑出了问题，并且饥饿使得他们同类相食。他们有着自己的语言沟通，因为饥饿导致他们大部分人营养不良，智力低下。',
    subraces: [
      {
        id: 'cannibal_brute',
        title: '食人族大只佬',
        description: '粗野巨躯的大型食人族，他的大脑相对于其他亚种更为愚蠢。初始属性修正：体质+20、智力-35、感知-15。',
      },
      {
        id: 'cannibal_warrior',
        title: '干瘦食人族',
        description: '体态干瘦却动作迅猛的的他们，一般属于食人族中的炮灰。初始属性修正：敏捷+15、智力-20、体质-10。',
      },
      {
        id: 'cannibal_priest',
        title: '食人族祭师',
        description: '食人族中最为聪明的存在，至少他们会讲人类的语言。初始属性修正：智力+15、体质-15。',
      },
    ],
  },
  {
    id: 'skeleton',
    title: '骨人',
    description:
      '骨人完全是个谜，没人知道他们来自哪里，又是怎么被创造出来的，但人们认为他们已经有几千岁了。他们有完整的感情，能感到悲伤，愤怒，激动，同情，震惊和快乐，但他们不能通过表情展示出来。他们没有偏见，无惧死亡，因此是勇敢无畏的战士。他们不会饥饿，不受天气效果影响，不游泳，直接在水下行走。',
    subraces: [
      {
        id: 'skeleton_roundhead',
        title: '圆头',
        description:
          '圆形脑袋是第二帝国时期生产的最为广泛的通用型劳工或民用骨人。它们的设计理念是“可靠与泛用”，光滑的圆形脑袋上没有任何多余的装饰，结构简单，易于维护。它们的身体构造均衡，能够胜任从耕作、建造到基础战斗等各种任务。过于朴实的设计也意味着它们缺乏在特定领域的专精能力，学习高级技能时效率略逊于其他专业型号。',
        attributeSummary: '力量+3、敏捷+3、感知+3、体质+3、意志+3、智力+3、魅力+3',
      },
      {
        id: 'skeleton_camera',
        title: '摄像机',
        description:
          '这些骨人是第二帝国时代的移动监视与数据记录单元，如今大多在古代遗迹或废弃的哨站中被发现。它们没有传统意义上的“头部”，取而代之的是一个包含了多种光学传感器的球状或盒状摄像机单元。这个单元赋予了它们超凡的感知能力，能在恶劣天气和光线不足的环境下精准地发现远处的威胁，这使它们成为优秀的远程射手和哨兵。',
        attributeSummary: '感知+15、体质-10',
      },
      {
        id: 'skeleton_lionhead',
        title: '狮头',
        description:
          '狮头是古代战争中用于突破敌方阵线的重型战斗机器人。它们以雄狮为蓝本设计的头部充满了威慑力，从脸颊两侧伸出的是用于散热和诊断的圆形金属管。它们的机体更为高大厚重，内置了额外的液压动力单元，提供了强大的力量。不过，这种蛮力特化的设计牺牲了机体的灵活性和速度，使它们在面对敏捷的敌人时显得有些笨拙。',
        attributeSummary: '力量+14、敏捷-12',
      },
      {
        id: 'skeleton_foxwalker',
        title: '狐行者',
        description:
          '狐行者是旧帝国时期被设计用于侦察与渗透的特种骨人型号。其最显著的特征是流线型的狐狸头颅结构与轻量化骨架，这使得它们能以高速度和寂静的脚步穿行于各种复杂地形。它们纤细的四肢内装有精密的平衡稳定器。作为代价，轻量化的设计牺牲了结构强度，使它们在正面冲突中难以承受重击。它们的处理器让其在野外拥有更强的生存直觉。',
        attributeSummary: '感知+5、敏捷+8、体质-10',
      },
      {
        id: 'skeleton_false_savior',
        title: '骨人-虚伪者',
        description:
          '外观、皮肤纹理与呼吸节律几乎与人类无异，连多数简易体检都难以识别其机械本质。其核心却是为高强度歼灭行动打造的古代战争单元，具备极端环境生存与持续作战能力。为了潜入与猎杀而存在，擅长在伪装与暴起之间切换，是第二帝国遗产中最危险的异化型号之一。',
        attributeSummary: '力量+10、敏捷+10、感知+10、体质+10、意志+10、智力+10、魅力+10',
        allowedGenders: ['male', 'female', 'other'],
        unlockScenarios: ['false_savior'],
      },
    ],
  },
  {
    id: 'ailu',
    title: '艾露族',
    description: '怪物猎人世界中的随行猫伙伴，敏捷灵巧，体型小巧。',
    hidden: true,
    subraces: [
      {
        id: 'ailu',
        title: '艾露族',
        description: '推荐身高 1.00m 的小型随行伙伴。',
      },
    ],
  },
  {
    id: 'canine',
    title: '犬类',
    description: '废土上常见的流浪犬族群，多以本能和饥饿驱动。',
    hidden: true,
    subraces: [
      {
        id: 'stray_dog',
        title: '流浪犬',
        description: '饥肠辘辘的小型犬类，敏感而谨慎。',
      },
    ],
  },
  {
    id: 'pack_beast',
    title: '驼兽',
    description: '商队常用的负重兽类，性情温驯而耐力惊人。',
    hidden: true,
    subraces: [
      {
        id: 'pack_beast',
        title: '驼兽',
        description: '常见的驮兽品种，可在恶劣环境中长途跋涉。',
      },
    ],
  },
];

export const TRAITS = {
  attribute: [
    {
      id: 'beak_legacy',
      title: '喙嘴兽血统',
      description: '你的脖子似乎比常人长了一截，总能提前看到远处的危险。感知 +3',
      category: 'attribute',
    },
    {
      id: 'keyboard_hand',
      title: '键盘侠之手',
      description: '虽然你身处废土，但你的手指似乎保留了某种每分钟敲击200次的肌肉记忆。敏捷 +5',
      category: 'attribute',
    },
    {
      id: 'skeleton_fanboy',
      title: '骨人狂热粉',
      description: '你喜欢在衣服里塞几块废铁皮假装自己是机械生命，虽然很重，但真的很抗揍。体质 +4',
      category: 'attribute',
    },
    {
      id: 'save_load_courage',
      title: '读档胆略',
      description: '你脑海中总有一个声音告诉你“死了可以重来”，因此你面对食人族也丝毫不慌。意志 +5',
      category: 'attribute',
    },
    {
      id: 'tech_hunter_glasses',
      title: '科技猎人的老花镜',
      description: '你戴上不知道哪捡来的眼镜时，突然对古代科学充满见解（虽然摘下后跟瞎子一样）。智力 +3',
      category: 'attribute',
    },
    {
      id: 'trash_talker',
      title: '嘴臭王者',
      description: '你精通各种废土粗口，还没开打就能把敌人气得失去理智，而你早就做好了逃跑准备。敏捷 +3',
      category: 'attribute',
    },
    {
      id: 'void_dead_muscle',
      title: '虚空死肌肉',
      description: '你看起来壮如牛，其实都是当初在虚荣谷吃不知名蘑菇催出来的，力气大但虚得很。力量 +5',
      category: 'attribute',
    },
    {
      id: 'holy_boomer',
      title: '圣国老保',
      description: '“赞美奥克兰！”你对某些教条有着刻板且极其顽固的坚持，精神极难被摧毁。意志 +4',
      category: 'attribute',
    },
    {
      id: 'hive_salesman',
      title: '蜂巢族代购',
      description: '“朋友，买个提灯吗？”你为了把破铜烂铁卖出去，练就了极其离谱的推销话术。魅力 +5',
      category: 'attribute',
    },
    {
      id: 'peeler_phobia',
      title: '剥皮机恐惧症',
      description: '只要看到长得像削皮机的东西，你的求生欲就会激发视觉潜能，洞察一切危险。感知 +3',
      category: 'attribute',
    },
    {
      id: 'brute_uninstaller',
      title: '蛮力拆卸工',
      description: '遇到不会解的锁或打不开的箱子，你的第一反应是用石头把它砸烂。力量 +4',
      category: 'attribute',
    },
    {
      id: 'squin_bar_slugger',
      title: '斯昆城街溜子',
      description: '长时间在斯昆城的酒馆里蹭吃蹭喝还要挨揍，练就了你比城墙还厚的脸皮和抗击打能力。体质 +5',
      category: 'attribute',
    },
    {
      id: 'swamp_haze',
      title: '沼泽大麻鬼',
      description: '吸入过多的沼泽迷雾让你对任何疼痛都反应迟钝，坏处是脑子有点慢，好处是稳如老狗。意志 +3',
      category: 'attribute',
    },
    {
      id: 'wasteland_expert',
      title: '废土砖家',
      description: '你总能用一套听起来非常有逻辑的废话，把路边的强盗忽悠得一愣一愣的。智力 +5',
      category: 'attribute',
    },
    {
      id: 'holy_filter',
      title: '自带圣光滤镜',
      description: '由于你长得比较顺眼，路过圣国哨站时守卫都愿意多看你两眼（甚至少收点过路费）。魅力 +3',
      category: 'attribute',
    },
    {
      id: 'berserker_no_brainstem',
      title: '脑干缺失的狂战士',
      description:
        '你把所有时间都用来挥舞重武器，肌肉填满了本该属于大脑的空间，数数超过10个指头就会头痛。力量 +10，智力 -9',
      category: 'attribute',
    },
    {
      id: 'paper_ninja',
      title: '废土纸片忍者',
      description: '你的速度快如鬼魅，但骨头脆得像饼干，可能一阵风就能让你骨折。敏捷 +10，体质 -9',
      category: 'attribute',
    },
    {
      id: 'wiki_cloud_player',
      title: '维基百科云玩家',
      description: '你脑子里装着整个世界的攻略和秘密，但长期脱离体力劳动让你变得手无缚鸡之力。智力 +10，力量 -10',
      category: 'attribute',
    },
    {
      id: 'ultimate_sandbag',
      title: '轮回谷的终极沙袋',
      description: '在重生镇当了十年奴隶，你的皮比盔甲还厚，但常年的殴打也让你关节僵硬，动作迟缓。体质 +10，敏捷 -9',
      category: 'attribute',
    },
    {
      id: 'save_reload_oracle',
      title: '读档预知者',
      description: '你似乎能预见“读档”前的未来以避开危险，但也因此十分依赖“重来”，稍有不顺就想放弃。感知 +10，意志 -10',
      category: 'attribute',
    },
    {
      id: 'oakran_zealot_extreme',
      title: '极致的奥克兰信徒',
      description: '你的信仰坚如神圣胸甲，但大脑也因此拒绝理解除了奥克兰圣典以外的任何复杂事物。意志 +10，智力 -9',
      category: 'attribute',
    },
    {
      id: 'hive_sales_king',
      title: '蜂巢传销之王',
      description:
        '你的口才堪比最顶级的蜂巢族商人，能把沙子卖给沙匪，但自尊心像玻璃一样脆弱，一句重话就能让你崩溃。魅力 +10，意志 -8',
      category: 'attribute',
    },
    {
      id: 'corpse_marathon_lifter',
      title: '尸体负重马拉松选手',
      description:
        '你热衷于最经典的“扛尸练级法”，获得了怪物般的力量，代价是你的注意力全在脚下，看不见前方的危险。力量 +9，感知 -8',
      category: 'attribute',
    },
    {
      id: 'persecution_sniper',
      title: '迫害妄想狙击手',
      description:
        '你总觉得有人要害你，因此练就了鹰一般的锐利视力，但你那多疑的眼神和鬼祟的举止让所有人都躲着你。感知 +9，魅力 -9',
      category: 'attribute',
    },
    {
      id: 'vanity_valley_idol',
      title: '虚荣谷的娇贵偶像',
      description:
        '你的容貌是这片废土上唯一的亮色，人见人爱，但身体也像温室花朵般脆弱，淋点酸雨就可能当场去世。魅力 +9，体质 -10',
      category: 'attribute',
    },
    {
      id: 'pathfinding_master_ai',
      title: 'AI寻路大师',
      description:
        '你总能找到地图的“最优解”，以诡异步伐高速移动，但这种非人感让你产生了严重的社交障碍。敏捷 +9，魅力 -8',
      category: 'attribute',
    },
    {
      id: 'mechanical_ascension_mania',
      title: '机械飞升狂热症',
      description: '你坚信“血肉苦弱，机械飞升”，用钢铁意志强迫自己无视痛苦，但也因此搞垮了脆弱的肉体。意志 +9，体质 -8',
      category: 'attribute',
    },
    {
      id: 'behemoth_slayer',
      title: '巨兽屠戮者',
      description:
        '你曾在没有重武器的情况下，硬生生用蛮力绞杀过一头成年的喙嘴兽。这种在生死边缘榨取出的肌肉爆发力远超常人。力量 +5',
      category: 'attribute',
    },
    {
      id: 'blade_tip_dancer',
      title: '刀尖舞者',
      description:
        '在地下角斗场里无数次的生死搏杀，让你学会了如何用最小的动作幅度避开致命伤，你的神经反应速度犹如绷紧的弓弦。敏捷 +5',
      category: 'attribute',
    },
    {
      id: 'eye_of_sandstorm',
      title: '沙暴之眼',
      description:
        '大沙漠的漫天黄沙没能吹瞎你的眼睛，反而让你能在能见度不足十米的沙尘暴中，精准捕捉到潜行强盗的微小足迹。感知 +4',
      category: 'attribute',
    },
    {
      id: 'shackle_breaker',
      title: '破铐者',
      description:
        '你曾在圣国重生镇的采石场服刑。那段暗无天日的绝望岁月没能压垮你，反而将你的精神淬炼成了真正的钢铁。意志 +6',
      category: 'attribute',
    },
    {
      id: 'ancient_relic_decoder',
      title: '古代遗物解密者',
      description:
        '在无数个伴随暗淡提灯的夜晚，你破译了大量科技猎手带回的第二帝国蓝图，你的大脑对机械与建筑有着超越时代的理解。智力 +4',
      category: 'attribute',
    },
    {
      id: 'wasteland_field_medic',
      title: '荒野游医',
      description: '你懂得如何用一卷肮脏的睡袋和几句暖心的话，安抚那些刚失去小腿的崩溃佣兵。魅力 +5',
      category: 'attribute',
    },
    {
      id: 'wasteland_cockroach',
      title: '废土蟑螂',
      description:
        '喝过酸雨，吃过腐肉，你这具身体已经对废土上90%的恶劣环境和劣质食物产生了抗体，你就是打不死的沙地小强。体质 +6',
      category: 'attribute',
    },
    {
      id: 'shek_milf_superfan',
      title: '沙克大妈狂热粉',
      description:
        '你对沙克族那些浑身骨刺、肌肉虬结的女性有着某种极其不可告人的狂热XP。只要一想到她们的肌肉，你就会像打了鸡血一样充满斗志。意志 +5',
      category: 'attribute',
    },
    {
      id: 'streaker',
      title: '果奔者',
      description:
        '你坚信衣服会是阻碍”。只有在全身一丝不挂的情况下，让废土的狂风抚摸你的肌肤，你才能跑出真实的自我。敏捷 +3',
      category: 'attribute',
    },
    {
      id: 'holy_nation_succubus',
      title: '圣国魅魔',
      description:
        '你深谙如何把一件破烂的“奴隶破衣”穿出欲拒还迎的时尚感。就算是满口“赞美奥克兰”的圣国老骑士，看到你也会红着脸偷偷咽口水。魅力 +8',
      category: 'attribute',
    },
    {
      id: 'masochist',
      title: '抖M',
      description: '你被打的时候发出了奇怪的喘息和娇喘声，甚至请求“再快一点”。你对疼痛的耐受度异于常人。体质 +8',
      category: 'attribute',
    },
    {
      id: 'swamp_meth_master',
      title: '沼泽绝命毒师',
      description:
        '你在沼泽地偷偷提纯大麻的时候，不小心吸入了过量的高纯度挥发气体。虽然这让你现在经常对着空气傻笑，但也让你在药理学上达到了奇怪的巅峰。智力 +6',
      category: 'attribute',
    },
    {
      id: 'scavenger_pose_method',
      title: '猛男/娇妻拾荒法',
      description:
        '你每次弯腰捡地上的破烂时，都会刻意撅起臀部或展现肌肉线条。这种诱惑力的姿态经常会让路过的强盗看呆，从而忘记打劫你。魅力 +6',
      category: 'attribute',
    },
    {
      id: 'blood_spider_symbiote',
      title: '血蜘蛛寄生共生体',
      description:
        '一只变异的血蜘蛛幼体寄生在了你的脊椎里。它与你的神经索相连，赐予了你全方位的雷达级探知能力，但这该死的小东西每天都让你感到痛苦。感知 +14，体质 -8，魅力 -8',
      category: 'attribute',
    },
    {
      id: 'overclocked_steroids',
      title: '超频类固醇',
      description:
        '你曾捡到并注射过一管发着绿光的第二帝国军用强化剂。你的肌肉膨胀到了随时可能撕裂皮肤的恐怖地步，一拳能打爆城门；但你现在肌肉十分肿胀，连自己系鞋带都做不到。力量 +12，敏捷 -12',
      category: 'attribute',
    },
    {
      id: 'desync_step',
      title: '卡死我了',
      description:
        '某天你一觉醒来，发现你移动会瞬间出现在某处，像是网卡一样。甚至掌握了卡进贴图、超越游戏渲染速度的究极步伐，但受到一点伤害就会特别特别痛，讲话也卡。敏捷 +12，体质 -8，魅力 -5',
      category: 'attribute',
    },
    {
      id: 'error_404_brain_dump',
      title: 'Error 404',
      description:
        '为了获取古代知识，你从不知道哪下的数据，插入大脑。你现在拥有了比肩顶级机械师的超凡智力，但你的语言中枢彻底损毁，一开口就是刺耳的乱码和电子噪音，没人愿意靠近你。魅力 -15，智力 +18',
      category: 'attribute',
    },
    {
      id: 'holy_nation_streetwalker',
      title: '圣国暗娼',
      description:
        '你曾经靠在漆黑的小巷里张开双腿换取干粮。你懂得如何解开男人的板甲，并用舌头和下体安抚那些伪君子。你擅长察言观色和伪装高潮，能在交媾的喘息间轻易摸走对方钱袋里的开币。敏捷 +3，魅力 +8',
      category: 'attribute',
    },
    {
      id: 'swamp_aphrodisiac_mark',
      title: '沼泽淫纹',
      description:
        '你幻想着娜尔可，某天发现肚子上出现淫纹。只要稍微摩擦或受到物理打击，就会让你到达顶点。你在战斗的剧痛中会不可抑制地流出水并达到高潮，将痛觉转化为极致的快感。体质 +12',
      category: 'attribute',
    },
    {
      id: 'xeno_stage_performance',
      title: '异种表演',
      description:
        '你曾在地下角斗场被奴隶主注射催情药剂，强迫与进行公开的表演。那群粗野蛮家伙的冲撞彻底改变了你的ASS。体质 +18，魅力 -10',
      category: 'attribute',
    },
  ],
  life: [
    {
      id: 'sand_chewer',
      title: '嚼沙者',
      description: '在大沙漠呆久了，你觉得饭菜里如果不咯牙、没点沙子，就完全没有灵魂。',
      category: 'life',
    },
    {
      id: 'prosthetic_collector',
      title: '假肢收集癖',
      description: '看到地上的断手断脚你会有莫名的兴奋，总想偷偷捡回背包里当手办拼起来。',
      category: 'life',
    },
    {
      id: 'blood_spider_ptsd',
      title: '血蜘蛛PTSD',
      description: '一到野外，你总觉得草丛里有红色的东西在爬，时不时就会神经质地跳起来。',
      category: 'life',
    },
    {
      id: 'slack_master',
      title: '摸鱼达人',
      description: '只要“老板”（屏幕外的玩家）的视线切到别的角色身上，你就会立刻停下手中的活开始发呆。',
      category: 'life',
    },
    {
      id: 'oil_addict',
      title: '骨人的机油瘾',
      description: '虽然你是血肉之躯，但你总喜欢没事偷偷灌两口劣质机油，尽管每次都会拉肚子。',
      category: 'life',
    },
    {
      id: 'beggar_chief',
      title: '丐帮帮主',
      description: '你对别人丢弃的破布烂衣有极高的鉴赏力，认为穿得越破在废土越有安全感。',
      category: 'life',
    },
    {
      id: 'lost_genius',
      title: '迷路天才',
      description: '只要没有明确的地图指示，你总能精准地带领小队走向最近的食人族营地或喙嘴兽巢穴。',
      category: 'life',
    },
    {
      id: 'camping_maniac',
      title: '露营狂热者',
      description: '你拒绝睡在有屋顶的酒馆里，只要有个破睡袋，你能在酸雨和毒气里睡得像个婴儿。',
      category: 'life',
    },
    {
      id: 'tax_paranoia',
      title: '被迫害妄想症',
      description: '你总觉得联合城的收税官躲在石头后面盯着你的钱包，每天都在数自己的开销。',
      category: 'life',
    },
    {
      id: 'animal_friend_oneway',
      title: '动物之友（单向）',
      description: '你总想去摸摸长颈鹿（喙嘴兽）和野狗的脑袋，完全忽略了它们只想把你当晚餐的事实。',
      category: 'life',
    },
    {
      id: 'wasteland_clean_freak',
      title: '废土洁癖症',
      description: '在苍穹之下皆是泥骨的废土，你居然有洁癖。别人打架是为了生存，你打架是为了抢肥皂。',
      category: 'life',
    },
    {
      id: 'bargain_compulsion',
      title: '砍价强迫症',
      description: '买个最便宜的原味绷带，你都要和商店老板拉扯半小时，只为了省下那可怜的1开币。',
      category: 'life',
    },
    {
      id: 'hallucination_clicker',
      title: '幻听者',
      description: '你总能听到天空中传来“咔哒咔哒”的声音（鼠标右键点击声），并下意识地跟着声音走。',
      category: 'life',
    },
    {
      id: 'dark_chef',
      title: '黑暗料理界新星',
      description: '你能把高级肉块和绿苹果炖出生化武器的味道，队友宁愿去啃仙人掌也不吃你的饭。',
      category: 'life',
    },
    {
      id: 'junk_tycoon',
      title: '废品大亨',
      description: '你坚信包里攒下的100个破烂铁丝和烂铰链，总有一天能换到一套大师级的武士护甲。',
      category: 'life',
    },
  ],
  fun: [
    {
      id: 'pathfinding_bug',
      title: '寻路AI故障',
      description: '有时候你会对着一堵墙或一块石头狂奔半小时，直到有人把你扛起来才能恢复正常。',
      category: 'fun',
    },
    {
      id: 'physics_tester',
      title: '物理引擎质检员',
      description: '当你被敌人击飞时，你有一定概率在空中鬼畜旋转，并像炮弹一样飞跃半个地图。',
      category: 'fun',
    },
    {
      id: 'save_guardian',
      title: '游戏存档保护伞',
      description: '遇到致命危险时，你不会求饶，而是会对着天空大喊：“玩家快按F5啊！快按F5！！！”。',
      category: 'fun',
    },
    {
      id: 'clip_master',
      title: '贴图穿模者',
      description: '你的背上的武器经常会长在你的后脑勺里，或者坐下时整个人陷进椅子里，但你习以为常。',
      category: 'fun',
    },
    {
      id: 'its_a_feature',
      title: '“这是个特性”',
      description: '无论遇到多倒霉、多违背常理的事情，你都会双手合十，用这句话来安慰自己和队友。',
      category: 'fun',
    },
    {
      id: 'beak_talker',
      title: '喙嘴兽语者',
      description: '你会惟妙惟肖地模仿喙嘴兽“嘎嘎”的叫声，虽然除了引来更多喙嘴兽之外没有任何卵用。',
      category: 'fun',
    },
    {
      id: 'camera_victim',
      title: '隐形摄影机',
      description: '你总觉得有个浮空的摄像头在以奇怪的俯视角度偷窥你，换衣服时你会对着空气竖中指。',
      category: 'fun',
    },
    {
      id: 'token_king',
      title: 'TOKEN大王',
      description: '你不喜欢说话和做事，因为那会消耗很多token。',
      category: 'fun',
    },
    {
      id: 'mod_conflict',
      title: 'MOD冲突受害者',
      description: '你偶尔会说出一大段乱码，或者主观上觉得自己变成了一个红色的巨大感叹号。',
      category: 'fun',
    },
    {
      id: 'peeler_spa',
      title: '剥皮机SPA爱好者',
      description: '你坚信剥皮人教派的削皮机只是一种比较深度的、略带刺痛感的“去死皮美容服务”。',
      category: 'fun',
    },
    {
      id: 'loading_reader',
      title: '加载界面阅读者',
      description: '你经常在跨越区域时呆立不动，眼神空洞，自称正在阅读“游戏提示：请不要招惹利维坦”。',
      category: 'fun',
    },
    {
      id: 'panel_anxiety',
      title: '属性面板焦虑症',
      description: '你每挥一刀、每挨一次打，都要低头看一眼自己的身体，焦虑地确认力量经验条涨了没有。',
      category: 'fun',
    },
    {
      id: 'cyber_psychosis_early',
      title: '赛博精神病早期',
      description: '自从装上了机械假肢，你就总想对着路过的无辜野狗释放什么“终极义体大招”（然而并没有）。',
      category: 'fun',
    },
    {
      id: 'official_translation_victim',
      title: '官方汉化',
      description: '你的语法倒装经常，说话像个机器人机翻“我运行在地狱”，别人听懂很难你的意思。',
      category: 'fun',
    },
    {
      id: 'skeleton_cosplay',
      title: '骨人Cosplay',
      description: '你喜欢戴个铁桶在头上，双手平举走路，到处对人说“哔哔啵啵，我是一个没有灵魂的机器”。',
      category: 'fun',
    },
    {
      id: 'regenerate_again',
      title: '重新再来',
      description: '遇到坏事时候，你不会难过，而是会内心会说：“我感觉不行，重新生成一下吧！”。',
      category: 'fun',
    },
    {
      id: 'weird_guy',
      title: '奇怪的家伙',
      description: '你总是对空气说话，优势时会说“继续”，逆风时会说“重新生成”。',
      category: 'fun',
    },
  ],
};
